### PR TITLE
Feather-Amspy

### PR DESCRIPTION
**Pull request by DefinitelyInconspicous**
I edited the tutorial feather. I tried making my own work from scratch but it was quite hard and didn't work out.
It was quite easy to learn, but got a little tedious after. It was a nice learning experience though!
 
Failed repo - https://github.com/DefinitelyInconspicous/indiBlot

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else (I edited the tutorial though)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

https://blot.hackclub.com/editor?guide=start

Lastly, link a picture of your art piece here:
Feather

### CODE REVIEW

**Comment by Ssmidge** [comment]
Hey!

I love your drawing!! Add on some more features! Maybe a quill? It's fully up to you!

I also noticed that it's not different between every run, one of our criteria is that it's algorithmic/generative, you could have the amount of lines on the feathers be random!

#### This isn't a flat out rejection, but it's pretty close to the feather tutorial, we'd still approve it if it's largely modified

**Comment by DefinitelyInconspicous** [comment]
Oh wait I just realised you said quill, not quilt 🤦 . It's fine though, right?

**Comment by Ssmidge** [comment]
It's better now! It changes on run which fits our generative/algorithmic! However, the main "attraction" of it is still the feathers, it would be really cool to see something that relates the feathers to the quilt!

**Comment by DefinitelyInconspicous** [comment]
Ok I made the feathers a "pattern" of the quilt using a grid layout, sorry for the delay. Been quite busy :)

**Comment by DefinitelyInconspicous** [comment]
Hi - are the changes I made sufficient or do I have to iterate more on it?

**Comment by DefinitelyInconspicous** [comment]
Ok I added rotation to the feathers

**Comment by Dongathan-Jong** [comment]
The code seems to be in an infinite loop when I run it! Please create a new PR once you have fixed your art. I closing this due to a new management system for the PRs.

**Pull request closed without merging**
