### PR TITLE
SinBall - Hrushal

### PR DESCRIPTION
**Pull request by Hrushal-Nikhare**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

Next, make sure you go through **each item** in the following checklist. Delete this line after!

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:

### CODE REVIEW

**Comment by Ssmidge** [comment]
Hey! I really love this! This is very cool (and trippy) to look at :D
There's one small thing though, changing the rotation to something higher (20s-30s) makes the wave count become smaller, is this intended?

**Comment by Hrushal-Nikhare** [comment]
Oh yea i forgot to patch that. while i was figuring out how to draw the waves i set a limit on the x that caused this

**Comment by Hrushal-Nikhare** [comment]
and now it breaks after ~45 degrees but due to the rotation func

**Comment by Hrushal-Nikhare** [comment]
Yep solved the issue

**Comment by Ssmidge** [comment]
Thank you for fixing it! Do you think you'd be able to work on it a little bit more? One of the first things that come to mind is some sort of sport ball (soccer, volleyball, etc), it'd be really cool to see something like that! You have a great base, the options are limitless :D

**Comment by Hrushal-Nikhare** [comment]
my original idea was to make the sine waves move inside the ball like an animation but couldn't do that with blot. and adding geometric patterns wont be hard but i dont have much freetime on my hands rn

**Comment by M0HID** [comment]
Hi there! This is a really cool project, but it needs to be generative! (i.e. it is different every time the code is run) Im going to close this PR for now, but once you are done with your edits please make a new PR and we can review it there! (This is due to a new way we are managing Blot PRs)

**Pull request closed without merging**
