### PR TITLE
Kafka-Hibino

### PR DESCRIPTION
**Pull request by artemisIsNotBeam**
I decided to recreate Kafka Hibino, the main character from the anime Kaiju no 8. I used an algorithm to create his hair. Coding this was a new and exciting experience for me because this is my first time coding artwork. During my experience I used AI to aid me a ton to help solve difficult math problems. 

- [ x ] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [ x ] I am submitting art that...
  - [ x ] is algorithmically generated (will change each time the program is run)
  - [ x ] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [ x ] is original (not copied from somewhere else)
  - [ x ] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Comment by Aryankpoor** [comment]
I am not a PR reviewer but please read [the given instructions](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
carefully and remove the space in your folder name

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Nice piece! 
This is pretty cool, but I think it could be more generative.
It would be nice if eyes and mouth had some randomness as well

**Comment by artemisIsNotBeam** [comment]
I have updated kafka to have variating eyes and mouth here is the view link:
https://blot.hackclub.com/editor?shareId=817ab69c-e851-4165-83e5-e52f14195075

**Review by qcoral — CHANGES_REQUESTED** [review]
Hi! It's great that you're combining your personal interests with Blot, however this art piece is a little simple. Most accepted submissions take 15-20 hours. Keep working at it!

**Comment by Dongathan-Jong** [comment]
Hey! I am closing the PR due to inactivity! Please create a new PR once you have updated your art!

**Pull request closed without merging**
