### PR TITLE
usaFlag-Gautam

### PR DESCRIPTION
**Pull request by codergautam**
Hi, I have been coding JS for a while now and this was fun to make, I made a US flag using Blot 
 13 stripes and 50 stars.
snapshot0

### CODE REVIEW

**Comment by leomcelroy** [comment]
I think this is almost there. Could you add some shading to differentiate the colors of the stripes?

**Comment by codergautam** [comment]
Sounds good, on it 🫡

**Comment by codergautam** [comment]
Update: added shading @leomcelroy 
Screenshot 2024-04-12 073619

**Comment by Lightshayan** [comment]
This looks great! The variable you added is great, and the shading looks good. Good job!

**Pull request merged**
