### PR TITLE
Greendale-Eamonn

### PR DESCRIPTION
**Pull request by JimmmithyOrSomething**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

This art is of the logo of Greendale collage from the amazing TV show Community. The drawing has a flag with the logo as well as some buildings in the background. inside the code editor you can change some settings: one lets you unlock the logo allowing the arrows to spin freely and they will be diffrent every time. Another thing you can change is that you can remove the background if you want more of a simple image. You can also change the flagMove option to let the flag flap in the wind making a diffrent shape every time you run it. I spent a long time on this as it was the first time I have drawn anything in java script but I really liked doing it and I think it came out really nice.

- [ x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [ x] I am submitting art that...
  - [ x] is algorithmically generated (will meaningfully change each time the program is run)
  - [ x] is your own work that is not copied from somewhere else
  - [ x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [ x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [ x] Doesn't overlap lines more than 5 times
    - [ x] Fits in the working area of 125x125mm
    - [ x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
greendaleSnapshot

### CODE REVIEW

**Comment by JimmmithyOrSomething** [comment]
I dont know how to get Vercel to deploy.

**Comment by BrightTheBackpack** [comment]
Dw about the vercel stuff

**Comment by JimmmithyOrSomething** [comment]
Sorry what do you mean by that?

**Comment by JimmmithyOrSomething** [comment]
@BrightTheBackpack sorry I forgot to tag you in my message. What do you mean by "Dw about the vercel stuff"? -thank you

**Comment by BrightTheBackpack** [comment]
dw = don't worry, don't worry about the vercel stuff, it doesn't really matter

**Comment by JimmmithyOrSomething** [comment]
@BrightTheBackpack Ok, thank you but dont I need vercel to run inorder for someone to get assinged to my pull request? Because last time that I did one of these it took a few days to get vercel to run and no one was added untill it was deployed. thanks again.

**Comment by BrightTheBackpack** [comment]
it would help if you changed your js file name to index.js though i think

**Comment by JimmmithyOrSomething** [comment]
@BrightTheBackpack Ok, thanks I did that. Is there anything else I need to do to get approved?.

**Review by qcoral — CHANGES_REQUESTED** [review]
I like the intentional design with this scene, but most of it is hard-coded. Would there be a way for you to generate it more algorithmically? I'll swing back around later

**Comment by JimmmithyOrSomething** [comment]
@qcoral Thank you so much for the suggestion. I went back and added a new feature where the flag will flap in the wind so it can be a diffrent shape every time it runs.

**Comment by JimmmithyOrSomething** [comment]
@qcoral Hello I was just wondering if I had to add anthing else after I put in the changing flag to get it approved? No rush to respond I just want to know if I need to do anything else. Thanks

**Comment by JimmmithyOrSomething** [comment]
@qcoral Hi, I was just wondering if I have to do something else to get my project approved as it has been a while and I have not gotten any new information. Thanks.

**Comment by Dongathan-Jong** [comment]
This could use more work! Currently only the flag is random, I would like to see the buildings in different spots, the graphic on the flag different! Please create a new PR once you have updated your art, keep working at it! I am doing this due to a new management system for PRs.

**Pull request closed without merging**
