### PR TITLE
Nightsky-Khushraj

### PR DESCRIPTION
**Pull request by khrj**
[GitHub repo](https://github.com/khrj/nightsky)

I'd initially struggled a bunch with the leaf tutorial back when blot originally came out - which is surprising, because I like to think I'm pretty familiar with JavaScript itself - but I guess I haven't really touched math much and this was pretty new.

I'd mostly given up on this before Arcade came out, but blot was a recommended project, so I decided to give it another shot.

I remember struggling with some of the old curve functions - the bezier, and resampling. `catmullRom` is much easier to use and worked very nicely here. 

## Art

There's 6 types of stars, the

- simpleStar
- crossStar
- classicStar
- classicStarUnfilled
- curveStar, and
- arcStar

Counts for each can be configured at the top of `index.js`. You can change if you want craters on the moon and if you want to rotate the stars, also at the top of `index.js`

image

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
I'm so glad catmull helped here! This art is a great start, but I think you can add a little bit more to it! what about some more details on the moon, or a starfield-like map:

Screenshot 2024-07-12 at 14 43 28

**Comment by matytyma** [comment]
You forgot to fork the repo and instead created a new one, check the [guide](https://youtu.be/AmbjNEPuv14) for more info

**Comment by BrightTheBackpack** [comment]
? ? ?
it is a fork... 
image

**Comment by khrj** [comment]
> You forgot to fork the repo and instead created a new one, check the [guide](https://youtu.be/AmbjNEPuv14) for more info

It is a fork, the repo is a copy for Arcade

> or a starfield-like map

I really like how that looks! I'll try to implement something like that, I'm not too sure how to go about doing it but I'll give it a shot

**Comment by matytyma** [comment]
My bad guys, I got confused by the beginning of the first comment ([GitHub repo](https://github.com/khrj/nightsky)) :sweat_smile:

**Comment by maxwofford** [comment]
@khrj the starfield stuff was just where my head went, but what i'm actually reviewing on is just how algorithmic your art is and how much variety it can generate. If you start working on that and end up with a totally different new feature than what I recommended I'll still review that all the same! Art is just [happy mistake after happy mistake](https://www.youtube.com/watch?v=Ht9LMYivBnM)!

**Comment by maxwofford** [comment]
Hey @khrj, just checking in on your PR– any updates?

**Comment by khrj** [comment]
hey! not just yet, but I will be working on this soon

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in over a month, I'm going to close the PR for now. You're free to make a new one in the future with the same artwork if you'd like! Happy Blotting!

**Pull request closed without merging**
