### PR TITLE
Ratio_Dependent_Pattern-Dexter

### PR DESCRIPTION
**Pull request by Speedlet2**
Hi everyone! This is a program I created for the Hack Club Blot that is designed to change depending on the aspect ratio of the art piece! At 1:1, the pattern is regular. However, at any other ratio the pattern changes. At a 1:1 ratio, the central pattern is designed to represent similar shapes found in architecture (and be partially similar to the look of petals on a flower, but I can understand if most people cant see it). You can see some of the different patterns formed by different aspect ratios in the .png files in the snapshots folder! I hope everyone enjoys this as it took a lot of figuring out the different positions!
image (1:1 ratio)

A few other ratios!
image (2)
image (3)
image (1)

### CODE REVIEW

**Comment by Speedlet2** [comment]
I have some experience with coding, having previously developed a couple of games for sprig, alongside school projects and a couple of other ideas I've had (including a python library and program designed to act similar to the Little Man Computer which interprets a proprietary version of assembly code)!. I constantly try to improve and having these amazing schemes to have a physical/visual output rather than just text has been helping me massively!

**Comment by Speedlet2** [comment]
I have now updated this pull request so that it is compatible with the engine changes since I first created this artwork

**Comment by leomcelroy** [comment]
Thanks for being on top of submitting this. I'm trying to decide whether it's overly abstract or not and was hoping to get other Hack Club Blot participants to give their opinions so it's not entirely based on mine.

**Comment by leomcelroy** [comment]
I believe we discussed else where about how to improve the piece. Closing this PR for now but looking forward to seeing the new submission.

**Pull request closed without merging**
