### PR TITLE
fractal_circle-Nicolas_Landucci

### PR DESCRIPTION
**Pull request by nicolandu**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Hey there! This looks pretty cool, but when I run it I don't see anything! Did you upload the correct code?

**Comment by nicolandu** [comment]
Yes, it runs on my end, just hogs RAM. Sometimes reloading is required. Check my scrapbook post at https://hackclub.slack.com/archives/C01504DCLVD/p1721789463165939 for a picture!
________________________________

**Comment by nicolandu** [comment]
@BrightTheBackpack, could you please merge the PR even though the file is quite demanding to render? Thank you!

**Comment by whatwareweb** [comment]
It did work on my end but it took forever to render and for some reason it did not show up in the preview, but I tried to print it and it worked. Not sure why that happened

**Review by maxwofford — APPROVED** [review]
This is looking great! Go ahead and [order your kit](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
