### PR TITLE
FragmentedHorizon-Aleks

### PR DESCRIPTION
**Pull request by Rand0m0User1**
I didn't really have ideas at first but decided to basically reference my slack pfp (@ rndm) which I made when attempting to learn basic photoshop lol. 

My artwork depicts a geometric/abstract approach to a sunset scene. The grid was a bit wack to work with and the code for it is probably not the cleanest approach, but I thought it made a pretty cool warped effect. The spiral was also tricky to get right, but after a good bit I finally got it to how I wanted it to look. As for the random catmullrom lines, I browsed the toolkit until I saw something cool I could potentially work with as abstract "rays" for the sun. The reflection is just a spin on how the gridlines function.

Since I've already took part in onboard and arcade, I think this is another awesome initiative - I definitely enjoyed it!

HAeZcTt

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on a physical machine (doesn't have lines overlap more than 5 times)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Comment by qcoral** [comment]
I _love_ the concept, but I think you can do even more with it. Try and have a go at refining it, I'll keep an eye on this and stay posted!!

**Review by qcoral — CHANGES_REQUESTED** [review]
I love the concept, but I think you can do even more with it. Try and have a go at refining it, I'll keep an eye on this and stay posted!!

**Comment by Rand0m0User1** [comment]
I'm not sure what else I could add 😭. Any suggestions? Not a lot more white space to work with.

**Comment by Rand0m0User1** [comment]
And is your request geared more towards the generative aspect or just overall what's in the design?

**Comment by Rand0m0User1** [comment]
And, of course, ty for taking the time to give it a review

**Comment by qcoral** [comment]
Not necessarily suggesting you have to, but some ideas could be to increase the variety in the generation or maybe adding some more features?? I'd love for you to just experiment with some new ideas and see how it goes.

**Comment by Rand0m0User1** [comment]
Alright. Sounds good. Not really much comes to mind in terms of generation but referencing some sunset themed art online I can probably try adding something resemblant of a mountain range. Maybe palm trees? Could also play around some more with generation. I'll get back to you when I'm finished. Thanks!

**Comment by Rand0m0User1** [comment]
Hey @qcoral, finally finished with some changes. 

Design changes:
I added some mountains and birds (using turtle to add variety in the features I'm using). 

Generative Elements: 
- sun adjusts for size and height
- catmullrom rays are dispersed more randomly to mimic real sunrays
- grid adjusts for size
- peaks and troughs of the mountains generate randomly
- the birds disperse in random locations as well

Parameters:
- bird size
- number of birds
- angle of the birds
- mountain height and spacing between the mountains

*These parameters generally do not need to change unless the canvas size is adjusted which is unlikely since most users will print at the max 125x125 size.

I'm hoping this covers what you were looking for. Thanks!!!

**Comment by Rand0m0User1** [comment]
Had nothing much else to do so I added some skyscrapers in the mix too. This adds a bit more variety to the sunset theme I'm going for.

**Comment by qcoral** [comment]
I love the new ideas you added!! Definitely feels like a full scene now, I'll be showcasing this at TampaHacks tomorrow. Congratulations! You can order your blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Comment by Rand0m0User1** [comment]
Thank you!! Can't wait to get everything up and running on my own machine : ). Good luck with the remaining PRs!

**Pull request merged**
