### PR TITLE
Map-Dimitris

### PR DESCRIPTION
**Pull request by Dimitris-Toulis**
This drawing generates a river with fishes, a city and some trees and bushes. The city consists of houses, roads and trees. I tried to make as many things as possible dependent on the seed while putting constraints to make sure that it is still nice looking 

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

image

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Super cool! This is pretty close to getting merged, but just a small thing, could you make the trees a little more tree-like? 

image

Maybe the bush size could be bigger + random! 

Once you have completed that, I can forward this to Alex for approval!

**Comment by Dimitris-Toulis** [comment]
Hello, I have changed the the way the trees look and have made the bush size random. Let me know if anything else is needed (if not I will update the screenshots too)
image

**Comment by EmperorNumerius** [comment]
Hey there!
I like this artwork its really cool and generative.
Unfortuneately it does sometimes overlapp with itself and draws a house on a road and a tree.
image (2)
If you could fix that i think you would be well on your way to getting a Blot!!!! :)

**Comment by Dimitris-Toulis** [comment]
@EmperorNumerius could you take a look at my fixes?

**Review by qcoral — APPROVED** [review]
Hey - sorry we left you in the dark, this is great and has been approved.

you can order your blot here: https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw

happy blotting!!

**Pull request merged**
