### PR TITLE
SnowBanquet-Ankita

### PR DESCRIPTION
**Pull request by eyestare**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

It's a bunch of snowflakes around a snowman! It's my first time doing this kind of thing, so I struggled and made a lot of changes at first, but it all got better very quickly!

- [X] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [X] I am submitting art that...
  - [X] is algorithmically generated (will meaningfully change each time the program is run)
  - [X] is your own work that is not copied from somewhere else
  - [X] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [X] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [X] Doesn't overlap lines more than 5 times
    - [X] Fits in the working area of 125x125mm
    - [X] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
snapshot3

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
This is great, but I think you could definitely add more to the scene. Keep working on this! I love the changing snow

**Comment by eyestare** [comment]
Hi! I made some changes, please let me know if it's okay!

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey! This is a lot better, but many of the elements are static. Could you make it vary more with each run?

**Comment by eyestare** [comment]
Hi! I made some changes to the code. Let me know if this works! :)

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey! I like the changes but it still isn't very generative - can you make the design change more based on random variables?

**Comment by M0HID** [comment]
Hi there! I’m closing this PR for now to clear up the repo. Once you’ve made your edits/improvements, please make a new PR and we can review it there!!

**Pull request closed without merging**
