### PR TITLE
BFVisualizer-NumberBasher

### PR DESCRIPTION
**Pull request by TvoozMagnificent**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!
This is a visualization of the execution of a brainfuck program. 

Note: I know the images are long, I just wanted to show that the program can handle multi-digit numbers. 
More optimizations can be made but I don't think it is necessary at this stage. 

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:
Brainfuck (obviously)

Lastly, link a picture of your art piece here:

### CODE REVIEW

**Comment by TvoozMagnificent** [comment]
hello?

**Comment by Dongathan-Jong** [comment]
Hey! Please read over the [submission guidelines!](https://blot.hackclub.com/submitting) Here you will find that your art piece lacks a few features, mainly it being generative. Just a note, please set your canvas size to 125x125.

**Comment by M0HID** [comment]
Hi there! I’m closing this PR for now to clear up the repo. Could you make your artwork more generative (random i.e. every time the code is run, the output is slightly different)? Once you’ve made your edits/improvements, please make a new PR and we can review it there!!

**Comment by M0HID** [comment]
Also, please remember the canvas has to be max 125x125!

**Pull request closed without merging**
