### PR TITLE
Birb-AyaanGrover

### PR DESCRIPTION
**Pull request by ayaangrover**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Comment by ayaangrover** [comment]
Hey Max, 

Thank you for the feedback. I have taken your feedback into consideration and adjusted the code accordingly. Please do let me know what you think of the updated code once you have reviewed it.

Sincerely,

Ayaan

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
nice improvements!
 How about making it so there's a random amount of birds on the branch

**Review by maxwofford — CHANGES_REQUESTED** [review]
Nice work! It's close, but there's still a line that's a little off here– I think the line for the tail is travelling with the pen down instead of up? Not sure, but it looks like this on my screen:
Screenshot 2024-08-02 at 11 47 07

Other then that, you should make it more generative! I like how the tail moves each time, but the rest of the bird should change shapes/sizes/patterns too!

**Comment by ayaangrover** [comment]
After almost two weeks of work, I have updated the code with the biggest update so far. Now, there are a random number of birds on each electrical line. There are also random number of electrical lines, between 1 and 3. Also, there is a random sized sun in the top left with a random number of rays and a random ray length. The birds leg length is random and the bird direction is random. As a bonus, in the console the code logs the unique ID assigned to the specific generation.

**Comment by ayaangrover** [comment]
I have updated the snapshots to display the most recent code update.

**Review by maxwofford — APPROVED** [review]
This looks so great now! Nice work. You can [order your kit here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
