### PR TITLE
Tesla-Sabya

### PR DESCRIPTION
**Pull request by Sabya19**
a cool cybertruck art
Screenshot 2024-03-30 190825

### CODE REVIEW

**Comment by leomcelroy** [comment]
Nice! I think you've earned your Blot.

If you are a teen you can order it [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw). It will take a little while before we can send it as we are still stocking our supply of parts.

**Comment by leomcelroy** [comment]
Can you fix the PR to have the right header and to name the images properly?

**Comment by leomcelroy** [comment]
https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#20-add-metadata-to-your-indexjs-file

And the image titles must not have spaces.

**Comment by Sabya19** [comment]
thanks,i made the changes

**Comment by leomcelroy** [comment]
I also realized that all the pictures seem to be the same. I should have noticed before offering the form.

Can you make them varied by parameterizing the art?

**Comment by Sabya19** [comment]
so i wont get the blot as i ordered it

**Comment by leomcelroy** [comment]
It appears the age verification submitted with this was invalid. I'll still merge the PR into the gallery but you will be ineligible for a Blot.

**Pull request merged**
