### PR TITLE
Colorful-Heart

### PR DESCRIPTION
**Pull request by MohammedMMC**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

It represents layers of love and emotion, symbolized by hearts within hearts, each uniquely colorful. Drawing the heart shape presented some challenges, but the process of creating it and experimenting with colors made the experience rewarding.

Next, make sure you go through **each item** in the following checklist. Delete this line after!

- [X] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [X] I am submitting art that...
  - [X] is algorithmically generated (will meaningfully change each time the program is run)
  - [X] is your own work that is not copied from somewhere else
  - [X] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [X] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [X] Doesn't overlap lines more than 5 times
    - [X] Fits in the working area of 125x125mm
    - [X] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
Look at the last checkbox you ticked! I think this art piece relies heavily on color, could you try working on it more?

**Comment by MohammedMMC** [comment]
generating a random hearts like this can be better? 
image

**Comment by MohammedMMC** [comment]
I tried making something different: a heart made of smaller hearts, where the number of hearts changes each time you run it.
image
image
image

**Comment by MohammedMMC** [comment]
Hey @qcoral! it's been a month and I'm still waiting for your feedback. :')

**Comment by Dongathan-Jong** [comment]
This still needs work! I would like to see more complexity in this piece. The more time you spend making your piece, the higher chance you will get! Please create a new PR once you have updated your art. I closing this due to a new management system for the PRs.

**Pull request closed without merging**
