### PR TITLE
FlowingCurrents-KfirElyahu

### PR DESCRIPTION
**Pull request by BoghosDavtyan**
Hi, I'm Kfir! This is my first time making art with JavaScript. I called it "Flowing Currents" because it was inspired by how wind or water moves. It was tricky to make the smooth, wavy lines fit inside the canvas, but I'm happy with how it turned out. The lines were made using Perlin noise, and they look like abstract pictures of natural stuff or even space energy. It was really cool to see how changing things like the noise scale and curve strength could completely change the picture. This project got me really interested in making more art with code, and I want to try more complicated designs in the future!

- [X] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [X] is algorithmically generated (will change each time the program is run)
  - [X] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [X] is original (not copied from somewhere else)
  - [X] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is super cool! You should change it up a little though– maybe seed the noise function with something random so it doesn't always generate the same thing, and include logic to prevent too many lines drawing over eachother. In the current configuration, the blot's pen will cut the paper if it goes over the same spot too many times.

**Comment by maxwofford** [comment]
This is one of my top submissions though– looking so good!

**Comment by BoghosDavtyan** [comment]
Done! I messed around with the parameters and added a MAX_OVERLAP parameter to fix that. I think setting it to 2 gives the best results, but let me know what you think.

**Comment by BoghosDavtyan** [comment]
@maxwofford Do I need to add or change anything?

**Review by qcoral — CHANGES_REQUESTED** [review]
This is really pretty! Could I ask that you make a couple edits?
1. Blot can't draw 800x800 drawings, maybe change it to 125x125?
2. Could you explain what the different parameters do in the file
Thanks!

**Comment by BoghosDavtyan** [comment]
@qcoral I changed the canvas to the 125 x 125 resolution and added new screenshots of the updated script.

Explanation of parameters:

1. GRID_SIZE: This sets how detailed the flow field is. A higher value means more detail but takes longer to compute.

2. CELL_SIZE: This is based on the drawing size and `GRID_SIZE`. It shows the size of each grid cell in millimeters.

3. NUM_LINES: This is the total number of lines the program will try to draw. More lines make a denser pattern but can also increase overlap.

4. LINE_SEGMENTS: This limits how long each line can be. Higher values mean longer, smoother lines.

5. NOISE_SCALE: This affects how smooth the flow field is. Lower values make smoother, more gradual changes, while higher values make the pattern more chaotic.

6. MARGIN: This keeps lines away from the edge of the drawing. Adjust this if you want lines to be closer to or farther from the edges.

7. MAX_OVERLAP: This controls how often a line can cross the same grid cell. Higher values allow more overlaps, which can make a denser pattern but may be harder on the paper.

8. noiseOffset: This adds randomness to the flow field, creating different patterns every time the code runs.

9. In the NURBS function, `steps` decides how many points are used to make a smooth curve. More points mean smoother curves but take more time to compute.

You can change these settings to get different effects. For example, increasing `GRID_SIZE` and lowering `NOISE_SCALE` will make more detailed flow patterns. Adding more `NUM_LINES` and `MAX_OVERLAP` will make patterns denser.

**Comment by Dongathan-Jong** [comment]
So sorry for the super long response time! I will forward this to Alex for approval, this can take anywhere from a couple days to a couple weeks. Please be patient. If you have any questions, you can always reply to this PR or DM me on Slack!

**Review by qcoral — APPROVED** [review]
Sorry this took so long! I absolutely love this piece, and I'm glad you added the extra features. Congratulations! You can get a blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
