### PR TITLE
Geometricthingthatlookscurvedbutisactallyallstraightlines-GavinSchultz

### PR DESCRIPTION
**Pull request by a-fun-gi**
Hello to whoever is reading this!

I decided to make a Blot program after getting Make: Volume 89 and reading the Hackclub article. I saw the Blot part and thought "Oh, thats damn cool!". I remembered some thing I had learned in math class in sixth grade; I couldn't remember what it was called, but I made a program that implements it on a cross. I think that my program meets all the requirments. What you are doing here is really cool.

Rock on! - A Fun Gi

Here is an example piece created with my program:
example1

ps. pls let me know if i did something wrong, i'm new at this!

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @a-fun-gi, this looks awesome! I used to draw these with a ruler in middle school. To get your submission approved, you'll need to add something generative about it, so every time it generates the art is different!

**Comment by a-fun-gi** [comment]
OK, if you change the ws variable it will look different, is that enough?

**Comment by a-fun-gi** [comment]
Or should I make the ws variable random?

**Comment by maxwofford** [comment]
@a-fun-gi check out [this piece](https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/BeautifulSaturn-AlexB/index.js) to see what I mean when I say random & algorithmic! Your stuff is algorithmic, but you should swap out WS with a random method & include a few other things to make it even more random! If you're looking for inspiration, one of my favorite sites is https://turtletoy.net/

**Comment by a-fun-gi** [comment]
OK, I'll work on that.

...

dumb question: how do I change my index.js file?

**Comment by a-fun-gi** [comment]
never mid I figured it out

**Comment by a-fun-gi** [comment]
OK, I changed it.

**Comment by a-fun-gi** [comment]
Here is a new screenshot:
example1

**Review by maxwofford — CHANGES_REQUESTED** [review]
OOoooh, this is looking good! I think you can take it a little further though– keep changing it up.

**Comment by a-fun-gi** [comment]
😃

**Comment by maxwofford** [comment]
Hey @a-fun-gi, just checking in. Let me know once you have an update!

**Comment by a-fun-gi** [comment]
Hey, sorry I haven't edited it in a while, but I've been busy. Finally got around to changing it up a bit.
Here is a new screenshot:
example1
Also I want to change the name of the piece to Supernova, how could I do that?

**Comment by Dongathan-Jong** [comment]
The cross in the middle looks a little out of place! Keep working at this, I would like to see more! Please create a new PR once you have updated your art, keep working at it! I am doing this due to a new management system for PRs.

**Pull request closed without merging**
