### PR TITLE
Tangere-InfinityCity18

### PR DESCRIPTION
**Pull request by InfinityCity18**
I really like playing around with functions so the math side of this was really enjoyable, but i gotta say that javascript made my experience painful at times, but maybe its just me.
Heres some pics:

2024-08-09-131523_hyprshot
2024-08-09-131122_hyprshot
2024-08-09-132815_hyprshot

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
This looks awesome! Please re-read the stuff you checked off though– you didn't do the following:

- is algorithmically generated (will **change each time the program is run**)
- is drawable on a blot (**fits in the work area** & doesn't overlap too much)

**Review by maxwofford — CHANGES_REQUESTED** [review]
It's cool, but you're still going outside the blue box! That's the area the machine draws in.

**Comment by maxwofford** [comment]
Screenshot 2024-08-09 at 14 04 24

Also if you run a pen over a piece of paper 20 times it'll cut the paper.

**Comment by InfinityCity18** [comment]
Ok, fixed, thanks for clarifying that, although i designed it with the fact that it can be easily customized by changing the constants at the top of the file.

Also, while zooming in, it is revealed that it is not that crowded with lines

Zoomed in:
image

Zoomed out:
image

**Review by qcoral — CHANGES_REQUESTED** [review]
Nice art piece! Math demos are always really cool, but it needs a little more to be a full Blot submission. Currently, I have no idea what's going on. Could you add some explainers in your index.js?

**Comment by InfinityCity18** [comment]
Hello, I've updated the file with a comment to briefly explain what is going on.
Is everything clear now?

**Comment by Dongathan-Jong** [comment]
I'm getting a weird error! The lines seem to be cut off. Keep working on this! Btw, your canvas size should be 125x125 as the blot cannot draw more than that. 
image
Please create a new PR once you have updated your art, keep working at it! I am doing this due to a new management system for PRs.

**Pull request closed without merging**
