### PR TITLE
Racoon- Siva

### PR DESCRIPTION
**Pull request by coder123902312478**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [x] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Comment by Siva941477** [comment]
Screenshot 2024-07-20 000039

**Comment by D99-1** [comment]
This looks very similar to [this](https://github.com/hackclub/blot/pull/708)

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Hi there! Like D99-1 said, its very similar to that other pr. It also doesn't meet the submission requirements because you've just copy and pasted some points! Take a look at the suggestions I provided on the other PR!

**Comment by maxwofford** [comment]
I haven't heard anything so I'm going to go ahead and close this. @coder123902312478, feel free to submit something else but if you remix something you need to include the link

**Pull request closed without merging**
