### PR TITLE
Enhancing Visibility: Changing Borpheus SVG Icon Color to Black for Clearer Tab Recognition

### PR DESCRIPTION
**Pull request by shyakachaste**
I modified the color of the shortcut icon SVG named "Borpheus" from white to black. This adjustment was made to enhance visibility, particularly when the tab is open. The original white color was causing visibility issues as it blended with the background, making the icon less distinct. By changing it to black, the icon now stands out clearly, ensuring a more noticeable and aesthetically pleasing appearance when the tab is active. This adjustment aims to improve user experience by making the icon more discernible and visually appealing within the interface.
borpheus

### CODE REVIEW

**Comment by maxwofford** [comment]
Fixes https://github.com/hackclub/blot/issues/270

**Comment by maxwofford** [comment]
Thanks for the PR @shyakachaste !

**Comment by leomcelroy** [comment]
Upon closer inspection I think this is not quite what we want as it changes the icon used in other places.

**Comment by maxwofford** [comment]
@shyakachaste are you up to change just the favicon?

**Comment by shyakachaste** [comment]
@maxwofford please tell me what i can help you,

**Pull request merged**
