### PR TITLE
FlowersintheSun-Aryan

### PR DESCRIPTION
**Pull request by Aryanwin**
- [yes] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [ yes] I am submitting art that...
  - [ yes] is algorithmically generated (will change each time the program is run)
  - [ yes] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [ yes] is original (not copied from somewhere else)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

This is my project, which creates a randomly generated sun and a randomly generated field of flowers. You can change the number of rays on the sun and the number of flowers on the field easily using constants at the top of the code. The sun changes size and location on each run of the code, and the location and order of the flowers changes with each run of the code, both randomly. This was a fun project to code, and it would be even cooler to see it drawn with blot.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is a nice start, but I think you can take it even further! check out some of the pieces [in the gallery](https://blot.hackclub.com/gallery) for inspiration, or my personal favorite https://turtletoy.net/

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
This is a nice piece, but I think it could be elevated!

- Try adding a background! Maybe some mountains, or trees
- Add some color! The color won't show up when your blot draws it, but it'll still be cool!
- Add stems to the flowers

**Comment by Aryanwin** [comment]
Hi! I made several changes over the past several hours. First, the flowers looked kind of "smooshed," so I made a little algorithm to make sure that they were always separated. I added a horizon, an
Screenshot 2024-07-23 at 12 44 17 AM
Screenshot 2024-07-23 at 12 44 07 AM
Screenshot 2024-07-23 at 12 43 58 AM
d also added a little forest with a variable number of trees that are green. I'd only used turtle thus far, and I decided to try and use the drawlines function for the trees, and it turned out to be quite a lot easier. Anyways, I'm proud of what the code is!

here's a share link: https://blot.hackclub.com/editor?shareId=bed87419-d029-467f-a898-4c3fc4ad0616
I've attached a few images

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
I think this is close! Could you also make the trees generative too, by adding stuff like random heights and random placements?

**Comment by Aryanwin** [comment]
Hi!
It took me a moment to figure out how to scale the trees, but I was able to figure it out! I had originally made the trees evenly spaced apart to look cleaner, but I randomized their x-placements as well. By the way, instead of randomizing only the heights of the trees, I randomized the size of the entire tree by the same amount to make sure that the trees didn't look skinny or stubby. Thanks!

Here's the share link: https://blot.hackclub.com/editor?shareId=52591f09-8914-4bda-bd45-287e850a39e2
Here are some pictures:
Screenshot 2024-07-26 at 11 44 29 PM
Screenshot 2024-07-26 at 11 44 47 PM
Screenshot 2024-07-26 at 11 44 38 PM

**Review by maxwofford — CHANGES_REQUESTED** [review]
Nice work, but I think you can take it further! Here are a couple ideas:

- Make the trees generate in different shapes/sizes
- Make the trees not overlap
- Make the sun generate in different configurations
- Add clouds!
- check out turtletoy.net for even more!

Most blot submissions to the gallery take about 15-20 hours of work (based on what the submitters to the gallery have told us), so you should keep working on your art until it's something you'd want to hang up on your wall.

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in over a month, I'm going to close the PR for now. You're free to make a new one in the future with the same artwork if you'd like! Reach out to me @ alexren on the slack if you have any questions!

**Pull request closed without merging**
