### PR TITLE
blotfont-geschmit

### PR DESCRIPTION
**Pull request by geschmit**
Hello! I am submitting my tool & library, called BlotFont, to be put on the Blot art gallery. This tool is the culmination of many late hours into sketching, parsing and converting hand-drawn symbols into a set of instructions the Blot can use to draw all sorts of letters and numbers(nearly everything a standard US keyboard can type).

Here are some pieces it's drawn:
> Blot poster concept(submission)
blotadvert
> BlotFont logo
blotfont_logo

None of this is done with SVGs! This is all being drawn by turtles.

In addition to glancing over the submission code, I suggest you also take a peek at the BlotFont [repository](https://github.com/geschmit/blotfont). This contains a less crunched code that may be easier on some eyes to read and view.

I thank you for your consideration in my art piece!

### CODE REVIEW

**Comment by V205Arduino** [comment]
Wow! Wonderful!
(I was actually trying to do this to.....)

**Comment by geschmit** [comment]
This may be what's causing the icon not to load. Running it locally is being problematic for whatever reason...

**Comment by geschmit** [comment]
All changes requested have been made- the branch is ready to now merge.

**Comment by leomcelroy** [comment]
Great work! 

You can [order your Blot here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw).

We're still sorting out shipping logistics so be patient but we're really excited to get the machine to you and hear your experiences with it.

**Pull request merged**
