### PR TITLE
hackTV-Akhil

### PR DESCRIPTION
**Pull request by arp2019-Dev**
Making this was challenging but fun, I learned a lot about js through it even if it wrecked my brain a lot. Originally i wanted to make a tv that displayed the hack club logo but I decided to go a different route and instead wanted to create 3 channels, one was a figure holding up a bolder that is on an upside down hill (don't ask why it ended up like that it started out as an error but I though it was unique). The second one is just the regular old static using a bunch of random lines and lastly a grid matrix that could be used as an actual display ig.

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
This is pretty cool! One little nitpicky thing is have some sort of check to make sure the static doesn't go out of the TV.

**Comment by arp2019-Dev** [comment]
i made the edits

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
nice! could you also make the tv itself more generative by making have a random size and placements, and maybe also make the antenna and knobs have random placements?

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in over 3 weeks, I will be closing this PR for now. Feel free to make a new PR with an updated submission in the future!

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in over 3 weeks, I will be closing this PR for now. Feel free to make a new PR with an updated submission in the future!

**Pull request closed without merging**
