### PR TITLE
JJK_quote_Generator-Yashas Singh

### PR DESCRIPTION
**Pull request by YashasSingh**
Hi my project is a quote generator which essentially takes a quote from a show called Jujutsu Kaisen and draws an image of the person the quote is associated to.

I don't have too much experience with coding in js so it was definitely was a bit harder to work on.
Screenshot 2024-07-09 175415

### CODE REVIEW

**Comment by leomcelroy** [comment]
Thanks for the submission! Your folders seem to be duplicated. Can you fix that?

**Comment by YashasSingh** [comment]
yup done @leomcelroy

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @YashasSingh! This looks cool, but doesn't quite meet the [submission criteria](https://github.com/hackclub/blot/blob/main/docs/BLOT_REVIEW.md#submission-criteria), specifically about being algorithmic. While this technically chooses between characters and quotes, the actual text's code comes from another project and the character profiles come from preset data.

Could you play around a little more and really focus on making it stand out in interesting ways. One idea is you could dynamically make little cards like the borderlands loading screens where the quote is angled and cuts out of the image behind it.

**Comment by maxwofford** [comment]
I haven't heard anything so I'm going to go ahead and close this for now so it's not in my re-review list. If you want to keep working on it just let me know and we can re-open this PR for now!

**Pull request closed without merging**
