### PR TITLE
mycoBuild - ManaalLakhani

### PR DESCRIPTION
**Pull request by ManaalL**
very new to coding, did a python and java courses in school before but first time coding in JavaScript.

my artpeice is inspired by a project im working on to help people grow mycelium based composites so i just wanted to draw a mushroom :) (looks v simple but took me so long to make lol)
mycoBuild1

### CODE REVIEW

**Comment by leomcelroy** [comment]
This is great. Just the sort of thing I was hoping people would try to make. It would be nice to see the variation in the mushroom itself.

Congrats, you've earned a Blot. You can order it [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw).

You misnamed your snapshot in the metadata but I just fixed it for you.

**Review by maxwofford — CHANGES_REQUESTED** [review]
Woah, this is so sick! I absolutely love it.

- Could you rename your [folder from the guidelines](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#22-place-your-program-in-a-folder-with-at-least-3-snapshots) so I can get this merged?
- Also I appreciate the circles regenerating but they go outside the box! That'll mess with the robot so you should scale your art down a little (check out the scaling function)
- the mushroom itself isn't generated so I can't quite count this as generative art. Have it change a little (ie. longer/shorter stim, different number of gills) with each generation and I can approve it!

**Review by maxwofford — CHANGES_REQUESTED** [review]
Thanks for moving the files around, but it looks like the mushroom is still the same each generation & it uses `Math.random()`. That'll bug out the machine if you use it! Let me know once you get those fixed

**Comment by ManaalL** [comment]
Hey hey!
After a lot of struggle and tinkering with the code, I managed to get it
without math.random and change up the size of the stem and cap of the
mushroom as well as the number of gills. I unfortunately couldn't get it to
fix when it randomizes, and sometimes the gills go outside of the cap after
a lot of struggle, so I hope it's fine that you have to press enter to get
the desired shape now.

I edited the code in the GitHub post instead of uploading a new thing. I
hope that's okay. Lmk if I'm still missing something or need to do anything
else!
https://github.com/hackclub/blot/pull/641/files
<https://igafnl.com/click?redirect=https%3A%2F%2Fgithub.com%2Fhackclub%2Fblot%2Fpull%2F641%2Ffiles&dID=1722702533617&hashId=4f3196324e473b12491ca124edd4d6fc9629a218592f124e11650b3554f33c5e990813&linkName=https://github.com/hackclub/blot/pull/641/files>

Tysm for your time in advance and cant wait to use a blot soon :)

**Comment by BrightTheBackpack** [comment]
(just an fyi, you can use bt.randInRange as a substitute for math.random)

**Comment by ManaalL** [comment]
Hey, just following up on this, was my blot approved?

**Review by qcoral — CHANGES_REQUESTED** [review]
This is fantastic! It's *this* close to being merged, could you just clip the final polylines to make sure they stay witihn the 125x125 area?

**Comment by Dongathan-Jong** [comment]
Closing this PR due to inactivity! Please create a new PR when you update your art!

**Pull request closed without merging**
