### PR TITLE
Tetris-Naainz

### PR DESCRIPTION
**Pull request by Naainz**
- [X] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [X] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [X] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [X] is original (not copied from somewhere else)
  - [X] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

My generative artwork is inspired by the game "Tetris". The artwork features a grid of 10 columns and 20 rows, representing the playing area of tetris. The bottom 10 rows are stacked in randomly generated blocks. 

The top section of the grid, the single block (tetromino) is randomly placed to simulate a game. It can be placed in one of the 7 shapes: I, O, T, S, Z, J, or L. 

Creating this Tetris-inspired game was quite exciting and really helped me learn more about js syntax and logical thinking. I spent about 1 hour, 30 minutes on this  project. I learnt so much more about Blot's random functions, bt.rand(), etc. syntax unknown to me, previously.

### CODE REVIEW

**Comment by Naainz** [comment]
Accidentally merged and removed my art files too 💀💀, should be fixed now.

**Review by qcoral — CHANGES_REQUESTED** [review]
This is great! I like the clean implementation of the tetris pieces. I think you can add some more and really make this a whole experience though. Imagine a score tracker based on how full the grid was! This has a lot of potential and I'm excited to see what you do next.

**Comment by Naainz** [comment]
Hey! I think I've created something that quite well resembles your requested changes.
img1
The score value is determined by the total number of cells that are filled with tetromino pieces on the grid.

**Review by qcoral — APPROVED** [review]
Good work on the improvements! I really like this piece, consider it approved. You can order your Blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
