### PR TITLE
NotIshi28 - PepeMosaic

### PR DESCRIPTION
**Pull request by NotIshi28**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

Next, make sure you go through **each item** in the following checklist. Delete this line after!

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
https://cloud-ftbtw2yyz-hack-club-bot.vercel.app/0image.png

### CODE REVIEW

**Comment by blazecoding2009** [comment]
Hey @NotIshi28 

Good project but would you mind adding a bit more randomness to it? I can only see the colors moving around but not much else

**Comment by NotIshi28** [comment]
Hey @blazecoding2009

It's not just random colors, but there are randomly spawning squares as well

**Comment by blazecoding2009** [comment]
It doesn't seem to be working on my side then, I redrew roughly 3 times

**Comment by NotIshi28** [comment]
Hey, You can try it out here:
https://blot.hackclub.com/editor?shareId=3f77b7c6-5ffe-46ed-b096-3fdf90d70e22
You might be looking at the wrong version!

**Comment by Dongathan-Jong** [comment]
The link given seems to only generate 3 squares randomly, the rest is set in place! We are looking for more generative/random art, please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Pull request closed without merging**
