### PR TITLE
update browser compatibly warning and ENGAGEMENT.MD

### PR DESCRIPTION
**Pull request by V205Arduino**
I updated the browser warning and the Engagement.md

### CODE REVIEW

**Comment by V205Arduino** [comment]
Don't merge yet please.
I

**Comment by V205Arduino** [comment]
Ok!
Ready to merge!(I hope)

**Comment by leomcelroy** [comment]
Thank you!

**Comment by V205Arduino** [comment]
Welcome!
Thanks!

**Pull request merged**
