### PR TITLE
Radio-Neon

### PR DESCRIPTION
**Pull request by DeveloperNeon**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [x] Optional, if you used a tutorial or based your art on something else, please include the link here:
I based my design off of the [Motorola APX line](https://www.motorolasolutions.com/en_us/products/two-way-radios/project-25-radios/portable-radios.html) of radios.
- [x] Optional, if you remixed this from something else, mention it here:
I didnt remix someone else's design, but rather I used a minified version of [geschmit's BlotFont](https://github.com/geschmit/blotfont/tree/main). 

Ive been interested in radios for a good number of years now (I passed my amateur radio technician exam in 2018, and upgraded to general in 2023), and I thought I may as well make a radio. I was hoping to submit more, but I started to run out of ideas. If anyone has any ideas on things I should add, let me know!

If you're curious on what everything is, please see the picture below:
Re4xP7Gw1a81QSl

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
This is _really_ cool! I love it when people combine their interests with other projects to make something new. On that note though - I think you can make this even better, keep working on it and you'll get there soon!

**Comment by DeveloperNeon** [comment]
Hi @qcoral!

Thanks for taking the time to reply. Any ideas on things I should add?

**Comment by qcoral** [comment]
I dm'd on slack. Could I get an update on this?

**Comment by DeveloperNeon** [comment]
I have no dms from you. I reached back out over slack.

**Review by qcoral — CHANGES_REQUESTED** [review]
hey! love the new ideas but there's a couple instances where the text clips outside of the radio. 
image
Could you take a look?

**Comment by DeveloperNeon** [comment]
Should be fixed now!

**Comment by DeveloperNeon** [comment]
The frequency & channel name now pull from the [Repeater Book API](https://www.repeaterbook.com/wiki/doku.php?id=api).

**Review by qcoral — APPROVED** [review]
Great work on all the changes! Definitely learned something new reviewing this PR. This is _officially_ approved, congratulations! You can order your Blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
