### PR TITLE
PenguinsOnIce-saumil

### PR DESCRIPTION
**Pull request by saumilthecode**
So this is my third attempt at attaining a blot :D
so in this attempt I expounded on the last attempt by making the penguin draw abit more thicker so it looks more like a penguin. Other then that I also made the "cracks" in the background look more like cracks so its more like real penguins on ice :)
thanks for your time!

### CODE REVIEW

**Comment by saumilthecode** [comment]
yay

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is looking awesome! A couple things to fix though:

- currently it's drawing off the page– the machine can't do that!
- the penguins are drawn in white, but the machine can't draw in white! you should probably leave that unshadded
- There are some strange lines going up from the bottom of the page to the penguins. can you fix that?
- the snapshot file names shouldn't have capitals or spaces!

**Comment by saumilthecode** [comment]
Hello! @maxwofford could you take a look now?
I changed the snapshot file names, redid the colour the penguins are drawn in and made it respect the page boundaries! For some reason I can't manage to stop the trailing lines but I tried to and reduced the number of trails it makes

**Review by maxwofford — CHANGES_REQUESTED** [review]
I'm still seeing the strange lines coming up from the bottom. It's a little artistic looking, but also doesn't seem intentional!

Screenshot 2024-07-15 at 17 33 31

**Comment by saumilthecode** [comment]
Hello! @maxwofford 
so after experimenting, I decided a plain black belly looks the best. (The blank looks a bit weird cause of the way it reders)
I hope this gets approved!

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is getting closer! You still have some of those trailing lines, and I think the smaller penguins have their lines so close together it'll cause the pen to tear through the page.
Screenshot 2024-07-18 at 11 34 45
Screenshot 2024-07-18 at 11 34 48

**Comment by saumilthecode** [comment]
hello! @maxwofford I changed it so smaller penguins don't have that issue anymore. So I left the trailing lines to remain still since it looks nice for some pieces!

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
I still think it would be nice to remove those lines(completely up to you though)
I found the cause of the line was that sometimes y2 would be NaN, so a quick patch fix would be to add someething like this around line 72:
        let [x2, y2] = intersections[k + 1];
        if(isNaN(y2)){
          y2 = y1
        }

**Comment by saumilthecode** [comment]
Hi! @BrightTheBackpack I finally figured out how to remove the lines thanks to your help!

would this be enough to get a blot?

thanks for your time!

**Review by BrightTheBackpack — APPROVED** [review]
I think this gtg! Max will be around in about a week to do a final review

**Comment by saumilthecode** [comment]
yay okie!

**Review by maxwofford — CHANGES_REQUESTED** [review]
This still isn't quite at the level you need to get to for a blot. Keep working on it and plz tag me once you're sure you've done something that'd hit the quality of the gallery

**Comment by saumilthecode** [comment]
Hello! @maxwofford I made large changes to how they look now!

I gave them eyes and larger flippers (hahahhaha flipper zero reference)

also, it is intended to not fill in the area since it would use up a (b)lot of link

hope this hits the bar!

**Comment by saumilthecode** [comment]
Hello! @maxwofford pinging again since a week has passed (I understand yall are really really busy) but could yall squeeze a look at my art in (I've been working on this on and off for nearly 2 months now (not counting the 2 other PR's which got closed for not meeting the criteria)

Thanks! :D

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey! Sorry reviewing took so long. Can you add a variable at the top that disables all colour/varying thickness lines? That would indicate what it looks like when it's actually drawn on Blot!

**Comment by saumilthecode** [comment]
ok! changing now!

**Comment by saumilthecode** [comment]
heyo @qcoral made the changes !1

**Comment by EmperorNumerius** [comment]
I think this is there
Alex will review it in sometime but i think you are there

**Comment by saumilthecode** [comment]
heartbreaking that its been 9 weeks now with nothing in the last 3 😔

**Comment by EmperorNumerius** [comment]
This is super cool but keep an eye on the Blot channel for something

**Comment by EmperorNumerius** [comment]
Also I totally see where you are from but do remember tha all of us are in highschool/just left
im really busy with colllege apps and other school work, and alex is working on hackpad and was at htn until today lol

**Comment by saumilthecode** [comment]
hullo!
would there be any way to get this fast tracked :p
I would really appreciate it if we managed to get a blot for our club day (3rd of October) :D
(if not then I guess we'll have to make do with printouts and videos)

**Comment by saumilthecode** [comment]
added iceburgs + scarfs + made em rotate + made em more "penguin-like"!!!11

**Review by qcoral — CHANGES_REQUESTED** [review]
nice job on this! I think it could still use more polish though. Beyond that - your program filename needs to be index.js. Could you change that?

**Comment by qcoral** [comment]
Closing this for now - make a new PR with your changes!

**Pull request closed without merging**
