### PR TITLE
Create snowMelt-elijahPierce

### PR DESCRIPTION
**Pull request by anomynous1225**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

Next, make sure you go through **each item** in the following checklist. Delete this line after!

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:

### CODE REVIEW

**Comment by EnterpriseGoose** [comment]
Hello! Sorry it's been so long. The main reviewer has been swamped lately, so I've been going through and checking the submissions.

It seems like you did not upload any files. Make sure you followed all of the instructions [here](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md). Also, make sure to rename your PR as just "snowMelt-elijahPierce" (remove the "Create " part) so that the bot making the preview link can detect your submission.

**Comment by EnterpriseGoose** [comment]
Oh, I just saw that you submitted another PR that has all your code. Can you please close this PR? Thanks!

**Comment by anomynous1225** [comment]
I have gone in and made a cloud randomized in the x axis for some and put a sun in the volcano pic I also renamed the file to index.js if there’s anything else to do please let me know Sent from my iPhoneOn Nov 13, 2024, at 12:00 PM, EnterpriseGoose ***@***.***> wrote:﻿
Oh, I just saw that you submitted another PR that has all your code. Can you please close this PR? Thanks!

**Comment by qcoral** [comment]
closing this since it's empty!! thanks @EnterpriseGoose

**Pull request closed without merging**
