### PR TITLE
indiaflag-Dibya

### PR DESCRIPTION
**Pull request by JARVIS-124**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [x] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [x] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Comment by JARVIS-124** [comment]
please approve

**Comment by JARVIS-124** [comment]
Can you approve it please

**Comment by JARVIS-124** [comment]
It's been.a week.now

**Comment by BrightTheBackpack** [comment]
B. your snapshots are empty, and they have spaces, and your folder name isn't how its speicified in GET_A_BLOT, and the snapshots are supposed to be in a folder called snapshots
C. In the PR, you did not link the tutorial you used
D. It isn't algorithmically generated(will change each time the program is run)

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in 2 weeks, I'm going to close the PR for now. You're free to make a new one in the future with the same artwork if you'd like!

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in 2 weeks, I'm going to close the PR for now. You're free to make a new one in the future with the same artwork if you'd like!

**Pull request closed without merging**
