### PR TITLE
warpspeed-asherlief

### PR DESCRIPTION
**Pull request by asherlief**
Hi, I'm Asher.
I have worked with Scratch lots but this is my first time using Javascript.
This reminds me of hyperspace in star wars.
It was tricky getting the lines to end on the edge of the document.

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

right

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
This looks pretty cool! What if you added a millennium falcon to it!

**Comment by avibryant** [comment]
I added the windows from the inside of the millenium falcon.

**Comment by asherlief** [comment]
I added the view from the cockpit.

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is a good start but you'll have to take it a little further. If you want it to be like starwars, maybe you can...
- add a cockpit
- add planets
- add a star map

**Comment by asherlief** [comment]
I gave it square buttons and a star map. I don't think it should have planets, though, because they would streak into lines like the stars>
image

**Comment by asherlief** [comment]
Hey, maxwofford, did you see my last rendition? I'd love to hear what you think of it.

**Review by maxwofford — CHANGES_REQUESTED** [review]
Thanks for the bump on this. I think it's much closer, could you update your screenshots though?

**Comment by asherlief** [comment]
@maxwofford done!

**Comment by asherlief** [comment]
@maxwofford, have you had a chance to look at this?

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey! This is much better than before, but I think you can still work on this a bit. Could you try making everything look more consistent? I.e more detailed stars

Sorry it took so long to review, it will be better moving forward!

**Comment by asherlief** [comment]
Thanks for the feedback, but I'm not entirely sure about what you mean by more detailed stars.

**Comment by Dongathan-Jong** [comment]
Currently there are just boxes floating around in the top + bottom! I think what Alex is trying to say is have more within those regions, make it more complex. Please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Pull request closed without merging**
