### PR TITLE
Harmonograph-Ansh

### PR DESCRIPTION
**Pull request by ansh3108**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Comment by ansh3108** [comment]
You can adjust the values p1, p2, p3, p4, f1, f2..... d1, d2.... To generate art just like a harmonograph does

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
This looks really cool! However, It doesn't quite look like the one's I've seen, like this one 
image
Do you think you would be able to get it a little closer?

**Comment by ansh3108** [comment]
I think that's a limitation of blot that it cannot draw this much thin lines, and I don't think the art can be changed further because that's the algorithm for Harmonograph. And for achieving a similar like this, you will most likely to adjust the values

**Comment by maxwofford** [comment]
@ansh3108 any update on this? I can't wait to see the next iteration!

**Comment by ansh3108** [comment]
@maxwofford this is the final version from my side! I don't really believe that it can go a bit further because of the limitations in blot.

**Comment by ansh3108** [comment]
oh, you have to adjust the values as i mentioned earlier

**Comment by ansh3108** [comment]
image


It kinda looks something like you mentioned

**Comment by ansh3108** [comment]
image


This's how it looks like when drawn with a blot!

**Review by maxwofford — CHANGES_REQUESTED** [review]
Screenshot 2024-08-12 at 13 29 29
What am I doing wrong here? I keep trying to run it and I just get a straight line

**Comment by maxwofford** [comment]
Oh, just saw your comment. Please update your code so it generates that without adjusting the values! if you have some adjustable variables you can also hook them up with the provided random function

**Comment by ansh3108** [comment]
Sure!

**Comment by ansh3108** [comment]
@maxwofford Done with the changes!

**Review by qcoral — CHANGES_REQUESTED** [review]
This art piece introduced me to something I've never seen before, which is pretty cool. I think it's great, but I'd love if you could add a small section in your code (maybe at the top?) just explaining what a harmonograph is and more about the whole piece in general (like why you made it etc). I'll swing back around soon!

**Comment by ansh3108** [comment]
alright! on it

**Comment by ansh3108** [comment]
Done! @qcoral

**Review by qcoral — CHANGES_REQUESTED** [review]
Better, but I still think you can explain more. Pure mathematic implementations are not very interesting by itself, but they have tons of value if you're able to use the visual drawing from Blot to help you explain the process. Maybe explaining what the functions/variables generally do?

**Comment by ansh3108** [comment]
Added!

**Review by qcoral — APPROVED** [review]
Nice job on the new changes! I like the descriptions, and it's definitely much more informative. Congrats, you can order a Blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
