### PR TITLE
IMPRINT-Teja

### PR DESCRIPTION
**Pull request by TSKoduru**
I've created a system to take in any png, jpg, or just a general image file and convert it into a series of instructions that BLOT can draw. I noticed that there were a few other projects like this, but I wanted to challenge myself to do it without any major libraries (The only one I use is Pillow.) I also tried to program the vast majority of it in JS, though I had to do some preprocessing in python.

I have a decent amount of experience programming, but I've only started using JS recently after doing the ODIN project (https://www.theodinproject.com/about). It was fun to get to use JS in a non-frontend context. Thanks for the opportunity! 
Articuno

### CODE REVIEW

**Comment by qcoral** [comment]
This is a really cool project! Could you send me your Slack? I'd like to @ you

**Review by qcoral — CHANGES_REQUESTED** [review]
This is a really cool project! Could you send me your Slack? I'd like to @ you

**Comment by TSKoduru** [comment]
Yeah of course, thanks for reaching out! My handle should be @Teja Koduru.

**Comment by Dongathan-Jong** [comment]
Just an update, I will be closing this PR. (I don't know if this PR was accepted or not as it has not been merged yet) Please create a new PR if this hasnt been accepted yet! We are doing this due to new management of the PR system.

**Pull request closed without merging**
