### PR TITLE
Wanted Posters

### PR DESCRIPTION
**Pull request by grandell1234**
My Blot creation is wanted posters. I spent a long time working on them because I created a "custom text engine" function so I could call (an example from my script): `drawText('WANTED', 50 * scaleX, 574 * scaleY, 63 * scaleX, 5 * scaleX);`
Every time you run the program a different wanted guy will appear with different facial features. It took about two months to get this completed, NOTE: A few weeks was spent planning what I wanted to make. 

I have plans for a future project that I think could be kind of fun for Club organizers, but after some playing around in the blot editor, I found that I really need an actual machine I can proto-type on to continue my work on that.

I would definitely recommend running the script yourself in the Editor, to see a bunch of the different faces you can get (as its randomized everytime).

Thank you for spending time reviewing my submission!

**I also want to note, that for the last thing you are marking off, "colour" is misspelled and should be "color" and in the line talked about if you used a tutorial or remix, there is an extra "used" before "based".**

- [X] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [X] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [X] I am submitting art that...
  - [X] is algorithmically generated (will meaningfully change each time the program is run)
  - [X] is your own work that is not copied from somewhere else
  - [X] is drawable through the editor(does not use outside tools)
  - [X] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [X] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [X] Doesn't overlap lines more than 5 times
    - [X] Fits in the working area of 125x125mm
    - [X] Doesn't rely on colour to look good

- [ ] If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
WantedPoster3

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey! I love the idea, but this piece falls under the bar due to simplicity. I would recommend making it so that it could change names and have a part on the bottom that says "REWARD: $XXX" with a different number each time! I also suggest you use BlotFont, an easier way to make art! Once you update your art I will be happy to re-review it!

**Comment by grandell1234** [comment]
Thank you, I will make the specified changes.

**Comment by grandell1234** [comment]
Hello @Dongathan-Jong, before I do a resubmit is this more what you are looking for. There is now a reward that changes every time, along with a name that changes every time. To make sure it always fits in the required spacing I have every first name the same length, along with the last name (5-7 characters):
```
const firstNames = ['JAMES', 'SARAH', 'DAVID', 'CHRIS', 'ALICE', 'EMILY', 'BRIAN', 'OLIVE'];
const lastNames = ['JOHNSON', 'MARTINE', 'GARCIA', 'WILLIAM', 'BROWNIE', 'JACKSON', 'MILLARD', 'ROBISON'];
```
Screenshot 2024-10-04 at 10 48 24 AM

**Comment by Dongathan-Jong** [comment]
Again, these are still pre-generated! I want to see something that has infinite possibilities, not random with a set number of cases.

**Comment by M0HID** [comment]
Hi there! I’m closing this PR for now to clear up the repo. As said by [Dongathan-Jong](https://github.com/Dongathan-Jong), please make the reward value completely randomised! Once you’ve made your edits/improvements, please make a new PR and we can review it there!!

**Comment by grandell1234** [comment]
Yes, but can I put a max on the reward (otherwise it just goes off-screen, and doesn't meet that requirement.)

**Pull request closed without merging**
