### PR TITLE
Circle Pack

### PR DESCRIPTION
**Pull request by Brelee2222**

### CODE REVIEW

**Comment by leomcelroy** [comment]
This is more of a tech demo but it's an interesting one to have. That being said can you improve your PR to describe what you've done.

**Comment by Brelee2222** [comment]
> This is more of a tech demo but it's an interesting one to have. That being said can you improve your PR to describe what you've done.

Should I put the description in a README file?

**Comment by leomcelroy** [comment]
You could do that but just writing a description here is also okay.

**Comment by leomcelroy** [comment]
Also snapshot should reference one of the file names in your snapshots folder.

**Comment by Brelee2222** [comment]
> > > Also snapshot should reference one of the file names in your snapshots folder.
> > 
> > 
> > wydm?
> 
> oh okay

It does 👍

**Comment by leomcelroy** [comment]
This 

`@snapshot: circlePacker`

should be this

`@snapshot: circlePacker.png`

**Comment by Brelee2222** [comment]
> circlePacker

👍

**Comment by leomcelroy** [comment]
Okay I fixed it for you. You can order your Blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw). Congrats!

**Pull request merged**
