### PR TITLE
lorenz-omay

### PR DESCRIPTION
**Pull request by Omay238**
The lorenz attractor. Simple, and description is in the code.

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [ ] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [ ] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

It does overlap, although not over a whole line, just points with intersections. I think it's probably fine.

image

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey there! This piece unfortunately falls short of our requirements. Please review our [submission guidelines](https://blot.hackclub.com/submitting) to verify this art is good for a PR! Once you update your art, I would be happy to re-review!

**Comment by Omay238** [comment]
I presume the issue is the overlap?

**Comment by Dongathan-Jong** [comment]
We look for pieces that are visually representative! Your artwork is generative, but is mostly just one function. Also, we look for pieces that are complex in both length and detail! Sorry for not mentioning this earlier, I completely forgot!

**Comment by M0HID** [comment]
Hi there! I’m closing this PR for now to clear up the repo. As mentioned by [Dongathan-Jong](https://github.com/Dongathan-Jong), we're looking for more artistic pieces! If you would like to resubmit, please make a new PR and we can review it there!!

**Pull request closed without merging**
