### PR TITLE
inkBlot-Pitabread8

### PR DESCRIPTION
**Pull request by Pitabread8**
My artwork represents a literal ink blot inspired, of course, by Blot! It took me a while to figure out how to create a realistic, messy ink puddle, but the toughest part was positioning and trimming the feather. After receiving feedback, I added a design to the ink bottle that's based on the fibonacci sequence. Overall, I had a lot of fun creating algorithmic art for the first time!

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [x] Optional, if you used a tutorial or based your art on something else, please include the link here: [original feather](https://blot.hackclub.com/editor?guide=start) and [original petal](https://blot.hackclub.com/editor?guide=leaf)
- [x] Optional, if you remixed this from something else, mention it here: N/A

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is a good start, but I think you can take it further! ie. Make that feather generative!

**Review by maxwofford — CHANGES_REQUESTED** [review]
Screenshot 2024-08-02 at 11 44 23

The pattern in the middle looks cool! Keep in mind though the machine draws in pen and might cut through the page if you have too many lines overlapping! Can you edit this part to not overlap itself too much?

**Comment by Pitabread8** [comment]
@maxwofford Does the current iteration look better?

**Review by qcoral — CHANGES_REQUESTED** [review]
I like the concept, but currently this drawing isn't drawable by Blot due to the use of different colours and fill. Can you add a variable that disables them while still making it look good?

**Comment by Pitabread8** [comment]
@qcoral For the overlap, is it okay if I do `fill: "white"`?

**Comment by BrightTheBackpack** [comment]
if you do that it won't actually do anything on the blot machine. i think bt.difference or bt.cut(tbh i'm not sure which one) could work

**Comment by Pitabread8** [comment]
@qcoral Does the current version look good?

**Comment by Dongathan-Jong** [comment]
This is still too simple! I would like to see more randomness, more complexity. Please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Pull request closed without merging**
