### PR TITLE
KochSnowflake-GuySandler

### PR DESCRIPTION
**Pull request by GuySandler**
This is a Koch Snowflake, a fractal that takes each side of every triangle that has been made so far, cuts it into thirds, then connects the 2 points in the middle of the line into an equilateral triangle and divides the length by 3, repeating for as many times as you want without crashing your computer.

I started by making 2 projects of simple drawings to learn some of the functions of the blot library. I then looked for some medium-difficulty fractals to make and found the Koch snowflake. I tried multiple ideas on how to get the fractal to generate, but after researching more I found that recursive functions work best for this by pretty much precalculating the drawing instead of fully drawing each triangle and saving the position on the way. This should be drawable on the blot as long as there aren't too many iterations

I have not used turtles in a while and this was a fun project.

Level3Detail

### CODE REVIEW

**Comment by leomcelroy** [comment]
Love to see a classic fractal. Because it's pretty well tread territory would you be able to invent your own fractal or implement a collection of well known ones?

**Comment by GuySandler** [comment]
I added 2 more fractals should I add more?

**Comment by GuySandler** [comment]
I added another one so I now have 4 total is it enough or should I add more?

**Comment by leomcelroy** [comment]
I'm not seeing these fractals. I mean implement more than just the koch snowflake.

**Comment by GuySandler** [comment]
I forgot to update the github, should be updated now

**Comment by GuySandler** [comment]
do I need to redo the PR?

**Comment by leomcelroy** [comment]
You need to add .png to the snapshot metadata filename.

**Comment by leomcelroy** [comment]
This `@snapshot: snapshot_1`

**Comment by GuySandler** [comment]
done

**Comment by leomcelroy** [comment]
Congrats on earning your Blot you can order it [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw).

**Pull request merged**
