### PR TITLE
cactus jack

### PR DESCRIPTION
**Pull request by atharvgups**
i made this cactus jack drawing with aditya aiyer...
we spent a while doing this and figuring stuff out and got what we were looking for when we set out to draw a cactus with blot
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
Making art inspired by artists is one of my favourite things to see, and a music artist is no different. I like the idea, but its a little simple; keep working at it!

**Comment by atharvgups** [comment]
Hey! Anything specific you think I should add that would get this approved for a blot? I'm kind of short on time too because I wanted to demo this blot in one of my hack club meetings. Thanks! :)

**Comment by qcoral** [comment]
Nothing specific! Your art should be directed by you. Keep at it!

**Comment by Dongathan-Jong** [comment]
Hey there! I am closing this PR due to inactivity, please create a new PR once you have updated your art!

**Pull request closed without merging**
