### PR TITLE
BurningShip-Marcus

### PR DESCRIPTION
**Pull request by Mineinjava**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [x] Optional, if you used a tutorial or based your art on something else, please in

clude the link here:
    - I used https://www.cesoid.com/fractal?al=burningship to help find interesting stuff for the snapshots.

- [ ] Optional, if you remixed this from something else, mentio
n it here:

This draws section of the burning ship fractal. 

I did my best to make generated images drawable--it uses dithering which plotters should be able to manage.

tinyShip 

wisps

Note the effects of the [Moire effect](https://en.wikipedia.org/wiki/Moiré_pattern) with this art.

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
This is really cool! I love this piece, but unfortunately it's not drawable by Blot; I tried to draw it here at HQ and it killed our servo! Would there be a way for you to make a version that is visually simpler?

**Comment by Mineinjava** [comment]
Hi,
Sorry about the servo. 

I can make some adjustments to the code to make it simpler?

How did the servo break? Too many short lines? I can try to optimize the generator to yield longer continuous lines.

**Comment by qcoral** [comment]
Hey, so sorry I didn't get to you sooner - I think it just overheated from all the short line segments, since it has to lift the pen up every time.

**Comment by Dongathan-Jong** [comment]
Hey there! I am closing this PR due to inactivity, please create a new PR once you have updated your art!

**Pull request closed without merging**
