### PR TITLE
Island-Scooterthedev

### PR DESCRIPTION
**Pull request by scooterthedev**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

Island
-------------------------------------
This is an Island that I created that has a boat, some waves, trees and houses. Everything in this is random, from the shape of the island to where the waves are, or even where the house is located. I am pretty experienced in JS, so this didn't take me that long to make (5 hours), but was definitely still a challenge and took me some time. Overall, it was super fun to make this!

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Nice art! Can you make sure the the houses and trees don't overlap. Also sometimes, the boat is on land.

**Comment by scooterthedev** [comment]
Thank you! I think I have made it so the houses and trees don't overlap, and that the boat doesn't hit the island. Let me know if this is good!

**Review by maxwofford — CHANGES_REQUESTED** [review]
This looks cool @scooterthedev! Unfortunately when I run it though it always generates the same way. Could you remove/remove the `bt.setRandSeed` for the PR?

**Review by maxwofford — CHANGES_REQUESTED** [review]
Screenshot 2024-08-02 at 11 18 55
Screenshot 2024-08-02 at 11 18 51

I'm also still seeing some collisions that don't look intentional. Keep working at it and maybe include some more details on the trees, waves, & house! If you're looking for inspiration check out turtletoy.net

**Comment by scooterthedev** [comment]
> This looks cool @scooterthedev! Unfortunately when I run it though it always generates the same way. Could you remove/remove the `bt.setRandSeed` for the PR?

What do you mean it always generates the same? If you change the seed, it will generate differently.

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey! Just checked - it does indeed generate differently when you change the seed, nice job on that. Regardless, I think you can add a lot more detail to this piece. Keep working on it!

**Comment by Dongathan-Jong** [comment]
Hey! I am closing the PR due to inactivity! Please create a new PR once you have updated your work!

**Pull request closed without merging**
