### PR TITLE
OldTV-Ernests

### PR DESCRIPTION
**Pull request by ErnGusMik**
# Old TV
snap0

I based this artwork on an image of an old TV I found online. This is my first time making art using code.
I would say that I've had quite a bit of experience coding. I have been coding for 5 years now, and created multiple web apps, websites, mini-games and AI models (as part of learning on Codecademy). This is one of my first projects after taking a ~6mo break.

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
Nice work on this! I love [old style TVs](https://www.youtube.com/watch?v=yEIA7uc1x5s)

This is a good start, but I bet you can take it further! What if you drew static on it, or generated a random scene that looks like it's from a movie or something?

**Comment by ErnGusMik** [comment]
snap0
Something like this?

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Hi I'm Bright, I'm taking over for Max while he's on the Boreal Express this week.
This is pretty cool, and I think it's almost there! Maybe consider making the scene a little bit generative too, like changing the sun's posistion, and maybe adding a car thats somewhere on the road.

**Comment by ErnGusMik** [comment]
I made the sun's x position random and created a car that has a 50% chance of spawning. How does this look?
snap2

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Very cool! What do you think about having a couple scenes that get randomly chosen every time its ran?

**Comment by maxwofford** [comment]
Sending a quick bump on this @ErnGusMik – do you have an update for your art?

**Comment by ErnGusMik** [comment]
Not at the moment, I've been kind of busy the past few days, but I will try and work on it today & tomorrow.

**Comment by ErnGusMik** [comment]
I added 2 scenes:
1. scene -- ocean with ship. The ship's second mast randomly appears and disappears.
2. scene -- my attempt at 'Chicagohenge'. The sun & car randomly appear & disappear.

**Comment by ErnGusMik** [comment]
@maxwofford any update on this?

**Review by qcoral — APPROVED** [review]
Hey - sorry this took so long to review. I love the new changes you've added, and I think it deserves a Blot. Congratulations! You can order it [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
