### PR TITLE
PizzaMaker--eminentquasar34

### PR DESCRIPTION
**Pull request by eminentquasar34**
My artwork depicts a pizza with various toppings. The pizza has a crust on the outer edge. Toppings include pepperoni, pineapple, peppers, mushrooms, and olives. One pizza design was created with the toppings manually placed. There is a function that can be called that enables the user to select how much of each topping they want and then randomly place the selected toppings on the pizza.

As for my coding experience, I am strongest in Python, but I still see myself as a beginner. In high school, I am also currently taking a course on Java. Lastly, I have some practice with HTML/CSS for developing the front end of websites. I have had very limited work with limited libraries, so having to fumble through documentation on my own this time was a new (and enjoyable!) experience.

perfectpizza

### CODE REVIEW

**Comment by leomcelroy** [comment]
I love the concept but think it may be a little too simple. One way to elevate it would be to really nail the different toppings. I think right now the mushrooms are most recognizable. What are all the toppings you could make and how could you create cute cartoony icons for them?

**Comment by leomcelroy** [comment]
Also instead of just overlapping the toppings try to make them cover each other (hint check out `cover` in the toolkit).

**Comment by eminentquasar34** [comment]
I improved the toppings to be more identifiable.

image

**Comment by eminentquasar34** [comment]
Here is the updated javascript file, as well as a screenshot of a random pizza generated.
[index(updated).js.zip](https://github.com/hackclub/blot/files/14964830/index.updated.js.zip)
Screenshot 2024-04-12 at 6 06 08 PM

**Comment by eminentquasar34** [comment]
I have made it so the toppings are now random for every single run. The folder names are also updated :)

**Comment by leomcelroy** [comment]
It would be nice to add some occlusion but I think you've earned your Blot. Congrats, you can order it [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw).

**Pull request merged**
