### PR TITLE
RetroTatooine-MahitMarri

### PR DESCRIPTION
**Pull request by MahitMarri**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!
I had no idea what to make at first and I only new how to make straight lines. I made a bunch of those lines in a way so that it made a curve. I did the same for the other side and since im a star wars guy i decided to add two suns. It was supposed to mimic the sky Luke Skywalker looked at in A New Hope. I spent a long time trying to add color but couldn't figure it out in the end, and some other things I spent a while trying to make work was the variables and loops for the placement of the lines (i'm mainly a html/css guy).

Screenshot 2024-08-17 at 11 18 07 AM

I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
 I am submitting art that...
 is algorithmically generated (will meaningfully change each time the program is run)
 is your own work that is not copied from somewhere else
 doesn't call Math.random() (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
 is drawable on Blot itself (doesn't have lines overlap more than 5 times)
 Doesn't overlap lines more than 5 times
 Fits in the working area of 125x125mm
 Doesn't rely on colour to look good

### CODE REVIEW

**Comment by Ssmidge** [comment]
Hey! Your art seems cool, but for it to be reviewed, it has to follow the naming scheme!
Your blot JavaScript file is named `project.js` instead of `index.js`, and your snapshots folder isn't fully lowercase, without your files being specifically named like this, your project won't show up in the gallery correctly :(
Have a look at the guide [here](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#20-add-metadata-to-your-indexjs-file)!

**Comment by MahitMarri** [comment]
Thanks for letting me know, if I make these changes later today will it get
approved?

**Comment by MahitMarri** [comment]
I fixed the misnamed files

**Comment by Ssmidge** [comment]
Thank you!
The two suns seem to collide with eachother sometimes, and even go outside of the drawing canvas, the blot can't do that!
I think you can take this even further, you should try to push the blot to it's limits (without breaking it :D), there's lots of unused space that you can use to add details!

**Comment by MahitMarri** [comment]
I fixed the problem with the suns overlapping and sometimes leaving the boundary. Ill see what i can do to make the empty space fill up

**Comment by Dongathan-Jong** [comment]
Keep working at this! Please create a new PR once you have updated your art. I closing this due to a new management system for the PRs.

**Pull request closed without merging**
