### PR TITLE
Maze by Neerav

### PR DESCRIPTION
**Pull request by BadPotato1007**
image
I have made a cool maze, that may or may not be possible to solve! it looks really cool ,and I plan to print this on a spcial type op paper that i have, so that the ink can be transfered to a mug! 
image

it should look something like this! would be really cool to get a blot to do this instead of a printer!

### CODE REVIEW

**Comment by BadPotato1007** [comment]
any updates?

**Comment by leomcelroy** [comment]
I really like the idea of printing it on a mug. I think this piece is a bit too simple as is though. How could you make it more unique?

**Comment by BadPotato1007** [comment]
do you have any ideas that I could try? I am not too good at this kind of coding, so in my opinios its actually pretty good hehe...

**Comment by BadPotato1007** [comment]
@leomcelroy or anyone? I dont really know what else to do, as this feels complex enough to me already hehe... A quick reply could get me my blot faster!

**Comment by kcoderhtml** [comment]
maybe see if you can make the corners curved? that would be rather cool and be more complex than a maze

**Comment by leomcelroy** [comment]
Maybe if you tried to wrap the pattern on an object. Here is a stylized version of that sort of approach.

Screenshot 2024-04-04 at 10 01 19 PM

**Comment by BadPotato1007** [comment]
@leomcelroy  I have absolutely no idea how to do that lmao. I know pretty basic programing. More of a hardware guy. I make drone, and run software that someone else wrote on them 😀. Maybe something simpler? You someone who could help me out?

**Comment by leomcelroy** [comment]
It is quite a bit more complex. Maybe try making the corners curved as was recommended.

**Comment by BadPotato1007** [comment]
I really have no other idea... nythong else that is very simple by your standards that I can do to get my blot approved please?

**Comment by GuySandler** [comment]
you can round the corners or add random generation

**Comment by leomcelroy** [comment]
Is this maze solvable? Can you show the route that solves it?

**Comment by leomcelroy** [comment]
I'm going to close this for housekeeping. Feel free to resubmit again latter.

**Pull request closed without merging**
