### PR TITLE
flagDrawer-appleflyer

### PR DESCRIPTION
**Pull request by appleflyerv3**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

my artwork represents how flags are comprised of multiple shapes and lines. 
my experience was that i learned more on how to code in JS and how to use maths to create random art

Lastly, link a picture of your art piece here:
snapshot0

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
This is a really intriguing piece. It's pretty cloe to being merged, could I just ask that you have a variable at the top that disables colour so I can see what it looks like when drawn by Blot?

**Comment by appleflyerv3** [comment]
> This is a really intriguing piece. It's pretty cloe to being merged, could I just ask that you have a variable at the top that disables colour so I can see what it looks like when drawn by Blot?

@qcoral no problem ill add that by 11am SGT

**Comment by appleflyerv3** [comment]
still waiting...

**Comment by qcoral** [comment]
Hey - sorry this slipped through the cracks!! this piece looks great, and nice job with the changes. You can request your Blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)!!

Also, make sure to check out #hackpad in the slack - it's another ysws I'm running (and I swear the wait time won't be as long as before....)

**Pull request merged**
