### PR TITLE
DellPowerEdge-Ssmidge

### PR DESCRIPTION
**Pull request by Ssmidge**
# Dell PowerEdge
A low-res representation of three Dell PowerEdge servers, most of these are found in homelabs :D

- [X] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [X] I am submitting art that...
  - [X] is algorithmically generated (will change each time the program is run)
  - [X] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [X] is original (not copied from somewhere else)

- [x] Optional, if you used a tutorial or based your art on something else, please include the link here: Based my art on my PowerEdge R720, an example image can be seen [here](https://cdn11.bigcommerce.com/s-017c0/images/stencil/1920w/products/12196/55018/R720_8bay2__25089.1578343171.1280.1280__67008.1584378162.jpg)
- [ ] Optional, if you remixed this from something else, mention it here:

R720

I wanted to design something that was related to homelabbing and my compute came to mind, since it's the most important part of the homelab (in my opinion!), I decided to design three different Dell PowerEdge servers, an R620, which is a 1U server, the R720 which is a 2U server and finally the R9XX series, which is 3U (I don't have an R9xx server so I'm hoping it's around the proper size).

The following items are randomized:
- The position of the server, mainly the height.
- The U size of the server
- The text on the server, either Dell or Dell EMC.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
Nice work on this! Love the detail. It looks like this can only generate a couple of configurations – what if you gave it a rack to live in. You can change the position of the server or add multiple to the rack. Oh, and route your cables or something!

**Comment by Ssmidge** [comment]
Hey,

I added a rack to it and a "2d" and "3d" style, mainly by changing the angle displayed for everything after the front panel. Let me know what you think!
For cables, I'm not really sure how I can achieve a 3D arc. :(

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
It would also be cool to have a random amount of servers stacked on top of each other!

**Comment by Ssmidge** [comment]
Hey! Thanks for your input! I added a 2nd server in the 0-degree angle version, it has a different size than the first server, but it's position is governed by the location of the first one. I hope it fits the criteria :D

**Review by BrightTheBackpack — APPROVED** [review]
Nice job! Max will be back in around a week to do a final review and then merge

**Comment by maxwofford** [comment]
Nice work on this! I really like that you changed up the orientation. I'm going to approve this & you can [order your kit here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Review by maxwofford — APPROVED** [review]

**Pull request merged**
