### PR TITLE
3D_Printer-Yash

### PR DESCRIPTION
**Pull request by yashsethu**
Hey! This is my blot project, it may seem simple, but I modeled it after my custom 3D printer, with some fun algorithms for the wire and generating the fan!

- [X ] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [ X] I am submitting art that...
  - [ X] is algorithmically generated (will meaningfully change each time the program is run)
  - [ X] is your own work that is not copied from somewhere else
  - [ X] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [ X] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [ X] Doesn't overlap lines more than 5 times
    - [ X] Fits in the working area of 125x125mm
    - [ X] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:
I got the idea from a 3D printer blot project on the gallery, but this was completely original

Lastly, link a picture of your art piece here:
image (1)

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
Oooo I really like this!! It's a really well made design. It feels a little simple in implementation though; what if you made it so it had a randomly generated 3D print next to the nozzle too, with layer lines? Or custom messages on the LCDs?? Or surprise me! It's your art piece, so anything is up to you. I'll come back around.

**Comment by yashsethu** [comment]
Hey @qcoral , I added the 3D print with print lines and the logo to my LCD! Lmk what you think!

**Review by qcoral — CHANGES_REQUESTED** [review]
Oo this is getting really close! 2 More things:

1. Could you make it so that the y-axis is also random so it changes every time?
2. Could you make it so the toolhead stays within bounds of the print?

If you could get that done, that would be amazing

**Comment by yashsethu** [comment]
Hey, you can uncomment the random y line to make the y-axis random, I just did this because I wanted to show the full print

**Comment by yashsethu** [comment]
@qcoral added your requested changes (#2) mostly

**Review by qcoral — APPROVED** [review]
Nice Job on the changes! Congratulations, you earned yourself a Blot. You can get it [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
