### PR TITLE
Starseed-SahandSoleimani

### PR DESCRIPTION
**Pull request by soleimanis**
This art piece of mine is called "Starseed" and the reason I chose this name was because it kind of looks like planting random stars on the canvas. 

We have our main star centered and static in the canvas, but the rest of a stars are all randomly generated and you can change the randomness of their generation through the "randomnessfactor" in the "Customizable Parameters" section.

This project was really exciting for me and I enjoyed the process of making my art piece a lot, so overall, Blot was amazing!

a

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
This looks great! Nice work on getting started. I think you can still mix it up a little bit more though. Check this out for inspiration: https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/BeautifulSaturn-AlexB/index.js

I just approved it a week ago & you should try updating your submission to be a similar level of complexity

**Comment by SahandSoleimani** [comment]
Hi, I hope you're having a wonderful day.

Tried my best to mix it up a little more so the main star also gets randomly generated.
Forgot to upload new snapshots tho, should I upload new ones or is that not necessary?

Thanks in advance.

**Review by qcoral — CHANGES_REQUESTED** [review]
This is pretty!! I also really like the documentation & comments within your code. I'd love to merge this, but it relies heavily on colour - is there a way you could make it as aesthetically pleasing using only lines?

**Comment by SahandSoleimani** [comment]
Hi, I hope you're having a wonderful day!

Thanks a lot, but I don't really understand what you mean by "it relies heavily on colour" and also the "using only lines" part, could you please elaborate further?

Thanks!

**Comment by Dongathan-Jong** [comment]
Currently you use the colour black to fill in spaces! Since the blot can only draw in one line, it can't actually draw with colour. Please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Pull request closed without merging**
