### PR TITLE
Flute-Apoorv

### PR DESCRIPTION
**Pull request by Apoorv010**
Hi! Here I attempted to create a flute with the help of the blot. The flute is decorated with a peacock feather.

As someone who has a lot of interest in making sketches and other stuff, the blot experience is great and it's fun to make different art pieces. I wish to turn this virtual art into real art on paper.

Snap1

### CODE REVIEW

**Comment by leomcelroy** [comment]
This is nice. Make sure the images folder is called `snapshots` not `Snapshots`.

**Comment by leomcelroy** [comment]
Also try to make use of `setDocDimensions` and center your drawing in the document. That way when people run it they'll be able to see it.

I like the added feather. There definitely could be a lot to learn making it look more realistic.

**Comment by Apoorv010** [comment]
Hi! Thanks for pointing the issues.
I have made the changes accordingly.

**Comment by leomcelroy** [comment]
Thanks for updating. Congrats on earning your Blot you can order it [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw).

**Comment by Apoorv010** [comment]
Thanks!!!😄😄

**Pull request merged**
