### PR TITLE
Grid_circles-Jakob

### PR DESCRIPTION
**Pull request by jakob07ffm**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Comment by jakob07ffm** [comment]
This I dont want to upload but dont know how to remove "art/RandomStars- Jakob/index.js"

**Review by Acidicts — APPROVED** [review]

**Comment by jakob07ffm** [comment]
Is there something I have to do??? Or only wait???

**Comment by Acidicts** [comment]
Dunno I just wanted to hit approve

**Comment by Acidicts** [comment]
I wonder when a hackclub blot maintainer will approve it

**Review by maxwofford — CHANGES_REQUESTED** [review]
OwO

looks like bubblewrap or something! I love it.

You're going to have to give it a bit more.... magic though.

Make it really change up and look interesting each generation! This is a good start but you should take it twice as far or more!

**Comment by jakob07ffm** [comment]
Ok I will try :)

**Comment by qcoral** [comment]
@jakob07ffm any update on this?

**Comment by Dongathan-Jong** [comment]
Hey! I am closing this PR due to inactivity! Please create a new PR once you have updated your art!

**Pull request closed without merging**
