### PR TITLE
LaTeXWriter-Kosei

### PR DESCRIPTION
**Pull request by splitlane**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

My art focuses on algorithmic and technical complexity, and it renders math by parsing the LaTeX markup language. I learned a lot through building a recursive parser (that parses strings, commands, etc), and the blot SDK was lots of fun. I will use this program to practice more integrals and make the pen plotter draw math!

- [X] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [X] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [X] I am submitting art that...
  - [X] is algorithmically generated (will meaningfully change each time the program is run)
  - [X] is your own work that is not copied from somewhere else
  - [X] is drawable through the editor(does not use outside tools)
  - [X] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [X] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [X] Doesn't overlap lines more than 5 times
    - [X] Fits in the working area of 125x125mm
    - [X] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
example1

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey - I think this is _awesome_!! I saw you have a TODO list in the file, would you be able to finish  the first 2? I think I'll definitely merge it then

**Comment by splitlane** [comment]
Got it, I've implemented the demo of all the features (there is a constant in the file (DEMO_N) to switch between the two demos). Nested roots are also implemented now. Thank you for the review.

**Comment by EnterpriseGoose** [comment]
Hello! I noticed in the second demo that fractions still aren't centered (the second item on your to-do checklist). Would you be able to fix that one last thing?

**Comment by splitlane** [comment]
Hello, I have finished implementing an algorithm to center fractions using recursion. It works for all of the cases.

As a note, last time I completed the top two items on the to-do list and deleted them from the list (so the first two items now became the third and fourth items if that might have been confusing).

**Comment by EmperorNumerius** [comment]
Hey there! I'm thrilled you think this is cool! I agree, it's definitely worth getting a Blot. I'll let Alex know it's ready to be merged.

**Comment by qcoral** [comment]
Hey - so sorry I missed this.

awesome job on the blot, you can order one [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Comment by splitlane** [comment]
Got it, thank you for merging.

**Pull request merged**
