### PR TITLE
CarEmblemGenerator-Cral-Cactus

### PR DESCRIPTION
**Pull request by Cral-Cactus**
This project is a Car Emblem Generator that creates and displays one of three randomly selected car logos - Toyota, Audi, and Renault - at random positions on a canvas. Each time the script is executed, it randomly chooses which emblem to draw and determines its location on the screen.
brave_IXoEpH39g0
brave_QNu8TGHQKJ
brave_TIdYNKqV8d
brave_dW2vGN2TdR

### CODE REVIEW

**Comment by leomcelroy** [comment]
Thanks for the submission. I like the idea but the emblems are a bit too simple. Could you make it more than single lines?

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @Cral-Cactus, this is a good start, but doesn't quite count for the "generative art" part of the [submission requirements](https://github.com/hackclub/blot/blob/main/docs/BLOT_REVIEW.md#submission-criteria). Think you can mix it up a little more than just choosing a different position and logo? What if you randomly generated a car around it that was a new card design every time (not just choosing from a list of premade cars)

**Comment by Cral-Cactus** [comment]
@maxwofford, so you just want to I make it generate random car next to car emblems and everything would be good?

**Comment by Cral-Cactus** [comment]
@maxwofford, could you give opinion? I created car which parts are fully random generated using bt.randInRange, is this what you wanted? Thanks
brave_YGOwFbmSk4

**Comment by maxwofford** [comment]
@Cral-Cactus that's a start, but the gif you're showing me doesn't look that randomly generated besides the placement of the car. What if you put the logo on the car and changed the same/porportions of the car each generation? For inspiration check out https://turtletoy.net/turtle/browse/love/0

**Comment by Cral-Cactus** [comment]
I think you don't see much random generation of the car because that's just the luck when I was recording the gif and yea seems like in the gif is too small but you mean to make the car bigger and inside the car body put smaller version of the emblem?

**Comment by Cral-Cactus** [comment]
Something like this?
image

**Comment by Cral-Cactus** [comment]
@maxwofford, what do you think?
brave_4kEj6mHzZe

**Comment by maxwofford** [comment]
This is getting closer, but I think you can go further. Here are a couple ideas:

- only show the tail spoiler sometimes
- give it bumpers! maybe even different types of bumpers randomly chosen
- what about wheel wells! Most cars aren't directly ontop of their wheels.
- You can even figure out how to raise the car a random amount & end up with a lowrider

**Comment by Cral-Cactus** [comment]
@maxwofford, sorry but I have no idea what kind of bumper to do so it fit. But I changed wheels and created suspensions with springs and made the spoiler spawn chance to be 50%
image

**Review by maxwofford — CHANGES_REQUESTED** [review]
Looking good, now update the PR!

**Comment by Cral-Cactus** [comment]
oh what how I closed it

**Comment by Cral-Cactus** [comment]
Thank you so much for reopening the PR, I updated it :)

**Review by Cral-Cactus — COMMENTED** [review]
Uploaded final version

**Comment by Cral-Cactus** [comment]
@maxwofford, is everything alright with the PR? 😃

**Review by BrightTheBackpack — APPROVED** [review]
Nice job! Max will be back in a week or so!

**Review by maxwofford — CHANGES_REQUESTED** [review]
Nice work @Cral-Cactus– it's coming together. I'm still not going to merge it yet though, you should come up with some stuff to add to it. We have a high bar for pieces getting into the gallery & I think you can still get it a little further

**Comment by Cral-Cactus** [comment]
@BrightTheBackpack @maxwofford wtf guys, 3 weeks you guys are telling me that it is good and ready to be merged and now you are throwing that I should do more changed??? This isn't how the life works nor fair in any case. I am pissed off because you guys lied me hardly which is not cool for you and that speak a lot for you what kind of persons you guys are. I am totally disappointed from you guys. Also while in the gallery there are lots of ars which are way worse. You can't be telling me that it is good and you are going to merge it and 3 weeks later with no any response in the chat you are changing your mind out of nowhere that you want more changes and that it doesn't fit your criteria that is just bs

**Comment by Cral-Cactus** [comment]
You can close the pr, i don't want to deal with you guys in any case nor listen your explanations how in those 2 weeks without replys only from bright you changed your decision and so on i will build my own blot, this kind of acting really cancelled me doing anything for blot project, i am sure leo would've done better than you

**Comment by Cral-Cactus** [comment]
ok give me time, I will do better car

**Comment by Cral-Cactus** [comment]
that is kinda weird logic which this bot have with image file names, should I rename them how it want them like from 2.png to 12.png and 3.png to 13.png?

**Comment by Cral-Cactus** [comment]
Anyways I will update the images and will just rename them

**Comment by Cral-Cactus** [comment]
Honestly that artwork check is weird, it always want to add 1 more number if artwork names are numbers only so I will just use letters

**Comment by Cral-Cactus** [comment]
that artwork check system is broken i literary tried everything :(

**Comment by Cral-Cactus** [comment]
I tried but still show that, this artwork check is indeed so broken

**Review by maxwofford — APPROVED** [review]
Nice work on this! don't worry about the failing tests, I can see your files are where they should be and the art shows up correctly in the editor. This is really awesome and def deserves a blot. Go ahead and [order your kit](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Comment by Cral-Cactus** [comment]
Thank you max and sorry for all troubles, have a nice day!

**Pull request merged**
