### PR TITLE
RamadanLantern-Moccisor

### PR DESCRIPTION
**Pull request by MohammedRSaad**
My art work is a simple Ramadan lantern. Ramadan lanterns are a Islamic cultural symbol in Egypt from hundreds of years. Kids enjoy playing with those beautiful lanterns each year during Ramadan month. The lanterns' size and number can be easily customized to create a new artwork.
image (2)

I spent some hours working on that artwork project. I first learned how to use the tools in the Hack Club's blot bot. I started to practice on some random shapes. Then, I made the lantern's outline and added the body details. I used the documentation to learn more about available functions. I am really looking forward to see it in the gallery. It was a great experience!!

### CODE REVIEW

**Comment by leomcelroy** [comment]
Nice! I like how the simple drawing evokes a rich culture. Can you rename the snapshots to not use spaces and make sure the image referenced in the file actually exists.

**Comment by MohammedRSaad** [comment]
I'm glad you liked the drawing. 
I'm not experienced with GitHub. Can you please tell me how to edit the names of the file? And I don't understand wish file you mean? I have included 3 images one of them attached to the above comment.

**Comment by MohammedRSaad** [comment]
I renamed the images. Please tell me what else I should do.

**Comment by BrightTheBackpack** [comment]
In your js file, the image referenced(ramadan_lantern.png) does not exist. consider changing that to image1.png

**Comment by MohammedRSaad** [comment]
Oh! I didn't notice this. I just have fixed this. Hope its ready for publishing now. Thank you for reviewing my art.

**Comment by leomcelroy** [comment]
Looks good to me. Congrats on your Blot, you can order it [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw).

**Pull request merged**
