### PR TITLE
muchroomForMushrooms-Xinyang

### PR DESCRIPTION
**Pull request by mrkingseasheep**
image2
Idk what to say really. Mushrooms look cool so I thought it'd be interesting to generate them. This was my first time using javascript (usually use c++ despite being trash at it), which is why the code looks... interesting. I'm usually more of a competitive coder, so stuff like making artwork and the other things at hack club have really been interesting to experience, not to mention fun. I guess something that I stumbled on was getting the right functions (bt.cut, bt.cover and bt.union) and I usually just tried everything until it looked right. The mushroom is randomly generated everytime, however, you can further customize it by changing the constants at the beginning of the code.

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on a physical machine (doesn't have lines overlap more than 5 times)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Comment by mrkingseasheep** [comment]
image2

**Comment by maxwofford** [comment]
This is awesome!
IMG_1655

**Comment by mrkingseasheep** [comment]
glad to hear you like it :D

**Comment by qcoral** [comment]
Though this is somewhat simple, it's really aesthetically coherent and looks like what it's intended to be. I especially liked reading all your comments! Could you fix a couple typos in the file? After that, I'll merge and send you the blot order form. Congrats!

**Comment by mrkingseasheep** [comment]
I've fixed the typos

**Comment by qcoral** [comment]
Thanks! You can order your blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
