### PR TITLE
SpotifyCodeDisplay-Aiden

### PR DESCRIPTION
**Pull request by DominantDuck**
This is a display of a scannable code that can visit special Spotify playlists. This project strengthened my understanding in Javascript.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is a cool start @DominantDuck, but currently can only generate the same barcodes each time because it's hard-coded to your github link. What if you made it pull that from an API?

Another option to make it generative is to have the hard-coded barcodes, but then make the wavey lines inside them different shapes or patterns for each so it's generative.

**Comment by BrightTheBackpack** [comment]
I found this thread about getting spotify codes that may be helpful https://community.spotify.com/t5/Spotify-for-Developers/How-to-generate-a-spotify-code-using-web-api/td-p/5452329

**Comment by DominantDuck** [comment]
@maxwofford @BrightTheBackpack Thank you for your suggestions. I could use the api to generate the img; however, I can't find an api that will convert the png file into an array of 0s and 1s, which will end up looking like this. Currently, I am having to generate the array with 0s and 1s on my end.
image

**Comment by maxwofford** [comment]
@DominantDuck I bet you can do that in JS! No API needed! Try playing around with the barcode data they give you in JS as a blob or image object.

**Comment by DominantDuck** [comment]
@maxwofford I am unable to use the Image object via the blot editor. However, this is what I have: `/*
@title: SpotifyCodeDisplay
@author: DominantDuck
@snapshot: spotify.png
*/


const { Turtle, trim, merge, cut, cover, rotate, scale, translate, originate, iteratePoints, pointInside, resample, join, copy, union, difference, intersection, xor, getAngle, getPoint, getNormal, bounds, nurbs, catmullRom, rand, setRandSeed, randInRange, randIntInRange, noise } = blotToolkit;

var height,width = 0;

function convertToBinaryImage(image, threshold = 128) {
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');

  canvas.width = image.width;
  canvas.height = image.height;

  ctx.drawImage(image, 0, 0);

  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const data = imageData.data;

  const binaryImage = [];
  for (let i = 0; i < data.length; i += 4) {
    const grayscale = data[i];
    const binaryValue = grayscale >= threshold ? 0 : 1;
    binaryImage.push(binaryValue);
  }

  return binaryImage;
}

function getDimensions (data) {
    let heightCount, widthCount = 0;
    heightCount = lines.length;

    if (heightCount > 0) {
        widthCount = lines[0].length;
    }

    height = heightCount;
    width = widthCount;

    console.log(`h: ${height}, w: ${width}`)
}

function parseBinaryData(data) {
    let individual = [];

    for (let x = 0; x < height; x++) {
      individual[x] = [];
      for (let y = 0; y < width; y++) {
          individual[x][y] = lines[x].charAt(y) 
      }
    }
  return individual;
  console.log(individual)
}

function draw(arr) {
    for (let x = 0; x < height; x++) {
          for (let y = 0; y < width; y++) {
               if(arr[x][y] === "1" && y < width-1) {
                   if (arr[x][y+1] === "1") {
                     drawLines([
                          [
                            [y,height-x],
                            [(y+1),height-x]
                          ]
                      ]);
                   }
               }
          }
        }
}

let playlist = '37i9dQZF1DWVA1Gq4XHa6U';

const image = new Image();
image.src = `https://scannables.scdn.co/uri/plain/png/ffffff/black/256/spotify:playlist:${playlist}`;

image.onload = () => {
  const binaryImage = convertToBinaryImage(image);
  console.log(binaryImage);
};

getDimensions(image);

const lines = image.trim().split('\n');

const dataArray = parseBinaryData(image);
draw(dataArray);`

**Comment by DominantDuck** [comment]
@maxwofford How can I receive the physical blot so I can test it?

**Comment by maxwofford** [comment]
I'm out this week, but @BrightTheBackpack is online and can help with review!

**Comment by maxwofford** [comment]
@DominantDuck I'm back in person and will review regularly each workday now. You get a blot by getting art approved to the gallery. Currently your art doesn't meet the requirements https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#1-make-a-unique-piece-of-generative-art

**Comment by maxwofford** [comment]
@DominantDuck Your artwork must be algorithmic! I know you included a couple image.txt files in your code people can pick from, but your code should take in something that more people can tinker with b/c it looks like the image.txt files are doing the bulk of the work converting an image to text already. Try getting it to process the image files, or hit an api endpoint for spotify barcodes

**Pull request closed without merging**
