### PR TITLE
CyberCity-MelonMars

### PR DESCRIPTION
**Pull request by MelonMars**
- [✔️ ] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [ ✔️] I am submitting art that...
  - [ ✔️] is algorithmically generated (will change each time the program is run)
  - [ ✔️] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [ ✔️] is original (not copied from somewhere else)

- [x] Optional, if you used a tutorial or based your art on something else, please include the link here:
This is based on some shader art I saw, _[City lights by Martin](https://github.com/projectM-visualizer/presets-cream-of-the-crop/blob/master/Geometric/City/martin%20-%20city%20lights.milk)_

Artwork:
This artwork is, as previously mentioned, based off of cyberpunk city lights at night, with many different colors, and flying cars sprawled throughout the city, as buildings mesh into blocks.

Coding experience:
I've been coding sort of off and on for the past 3 years, but very rarely in Javascript. For me, this was a real learning experience as before this, I hadn't ever really used a function or even a loop in js. I also haven't created algorithmic artwork before, and found this a really enjoyable experience.

snapshot2

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Cool art! This is a really good start. 
I think it would be pretty cool to make the streets in between the blocks more detailed by adding sidewalks and street lines!
Something like this would be cool!
image

**Comment by MelonMars** [comment]
Thanks.
I made the suggested changes, adding lanes, sidewalks, and stuff on roofs. Additionally, I realized I had committed the wrong code originally, without the support for skyscrapers, which I added. 
The attached screenshot is the new and improved version, with color taken out to improve readability.
Screenshot from 2024-07-21 17-16-34

**Review by BrightTheBackpack — APPROVED** [review]
Nice job! Some of the colors look a little weird but that won't matter when its drawn on the blot. Max will be back in about a week to do a final review and then merge

**Review by maxwofford — CHANGES_REQUESTED** [review]
@MelonMars I think you can push yourself a bit more then this. It's def a step further but not quite the level of getting it in the gallery

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in over a month, I'm going to close the PR for now. You're free to make a new one in the future with the same artwork if you'd like! Reach out to me @ alexren on the slack if you have any questions!

**Pull request closed without merging**
