### PR TITLE
lighthouse-SamB

### PR DESCRIPTION
**Pull request by SamuelB111**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

My art work is of a lighthouse. The strips move to different positions every time you hit run because of the bt.randInRange function. This was my first time coding and I am very proud about my work. 

Next, make sure you go through **each item** in the following checklist. Delete this line after!

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
updated snapshot 1

### CODE REVIEW

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @SamuelB111 

I love the idea but according to our guidelines, you need to add a bit more "purpose" to the randomness. Try making another thing on the light house random! Perhaps the way the light is facing or anything!

**Comment by SamuelB111** [comment]
Thank you I updated my code and now there is another degree of randomness.

**Comment by BrightTheBackpack** [comment]
not a reviewer, but it would be really cool to have the light rotate like a real lighthouse!

**Comment by blazecoding2009** [comment]
Hey @SamuelB111 

It's not what we're looking for sadly, try working on this more and create another PR!

**Pull request closed without merging**
