### PR TITLE
JackintheBox-Dylan

### PR DESCRIPTION
**Pull request by DylM0nster22**
Coding this was pretty hard i have very little coding knowledge  so I kinda based this on my last blot I made but I changed it a lot and the changes took me most of the day to make but I tried my best to make a kinda cool jack in the box artwork and the eyes change size the mouth slightly changes shape and size and the cone hat changes size all in all it was pretty fun to do
image

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is a good start, but try taking it further @DylM0nster22! what if you have a jack-in-the-box meal pattern that gets tiled in the background of the page, or some other pattern to spice it up

**Comment by DylM0nster22** [comment]
Thanks for the feedback I'll try to add something like that today

**Comment by DylM0nster22** [comment]
@maxwofford Like this
Screenshot 2024-07-13 210656

**Comment by maxwofford** [comment]
This is so close! I don't think it's quite aesthetically there though. If I generate a couple times, I should get something identifiable different every time. I had to zoom in on your snapshots to realize they were different. You can fix that by making the changes more noticable, or making more changes. What if sometimes the milkshake were a side of fries? or a shake + fries? Changes like that would really stand out

**Comment by DylM0nster22** [comment]
Ill try to make it so it will sometimes be fries with a random amount of fries or sometimes the shake

**Comment by DylM0nster22** [comment]
i changed it @maxwofford 
Screenshot 2024-07-14 113838

**Review by maxwofford — CHANGES_REQUESTED** [review]
Nicely done! It's just not quite there yet– try making it more aesthetically pleasing. Would you frame the current one and hang it up in your house?

**Comment by DylM0nster22** [comment]
hey i changed the fries so they look more like fries instead of twigs I hope that make it more  aesthetically pleasing @maxwofford 

Screenshot 2024-07-15 222511

**Comment by DylM0nster22** [comment]
@maxwofford

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Hi I'm Bright! I'll be temporarily filling in for Max while he's gone for Boreal.
I think this is really close, but I think you could make the fries a little more fry like. Perhaps take some inspiration from this piece: https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/french-fries-eric/index.js

**Comment by DylM0nster22** [comment]
@BrightTheBackpack i tried to do what you asked to make it more similar by adding things that looked like salt
Screenshot 2024-07-20 230905

**Comment by BrightTheBackpack** [comment]
I think it would also be nice if they were a little more square at the ends!

**Comment by DylM0nster22** [comment]
@BrightTheBackpack i changed it would this be better?
JackintheBox1

**Comment by DylM0nster22** [comment]
@BrightTheBackpack

**Review by BrightTheBackpack — APPROVED** [review]
Nice job! Max will be back in around a week to do a final review and then merge!

**Review by maxwofford — APPROVED** [review]

**Comment by maxwofford** [comment]
Nice work on this! Go ahead and [order your blot kit](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
