### PR TITLE
MoonlitRoad-Ben

### PR DESCRIPTION
**Pull request by SlightlyLessBigJimmy**
My art piece is titled "Moonlit Road" because it is exactly as it says, a picture of a road on a landscape, with a moon and stars. The piece will generate differently each time, with the horizon line changing, grass being drawn, the stars being placed, scaled, and shaped randomly, and the road will follow where it should be according to the horizon line. My favorite part is the moon, however because it will have a randomly decided phase based on 3 different moon types. During the process of making this piece, I learned a new language, Javascript, and a new use for programming, Art! I never thought about making pictures with code before this.

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Super sick piece! However, in some instances, the lines do go out of the canvas, could you fix that? I think it would also be super cool if you added a cloud or two in there :)

**Comment by SlightlyLessBigJimmy** [comment]
> Super sick piece! However, in some instances, the lines do go out of the canvas, could you fix that? I think it would also be super cool if you added a cloud or two in there :)

I don't see any of the lines going outside the canvas unless some values are changed to very high levels, do I need to put a cap on some values to prevent this? I just assumed people wouldn't make them that high.

**Comment by Dongathan-Jong** [comment]
I think it's with the box where the lines spawn in from, you can see sometimes it goes out of the canvas under the blue line. Also, the stars sometimes go into the hill. Once you fix these I can forward this to Alex for approval!
image  
image

**Comment by SlightlyLessBigJimmy** [comment]
> I think it's with the box where the lines spawn in from, you can see sometimes it goes out of the canvas under the blue line. Also, the stars sometimes go into the hill. Once you fix these I can forward this to Alex for approval! image image

I have fixed the issues now, and committed the changes to index.js, that should update it correctly, right?

**Comment by Dongathan-Jong** [comment]
Great thank you! I will forward this, please wait as there will be an update soon (anywhere from a couple days to a week) in this PR whether you need a bit more of you've been accepted! Great work :)

**Comment by SlightlyLessBigJimmy** [comment]
Thanks!

**Review by qcoral — APPROVED** [review]
This art piece is awesome! Thank you @Dongathan-Jong for reviewing this. Congrats on your new Blot! You can order one [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
