### PR TITLE
Minion-ChloeC

### PR DESCRIPTION
**Pull request by celloii**
Minion-Chloe Chen. My artwork attempted to replicate a minion from Despicable Me. It required lots of experimentation with the placement of each of the hands/glasses/clothes. I used a for loop to play around with extra add ons such as a hat and a flower. I have little experience with javascript and I had lots of fun playing around with it. 
snapshot2

### CODE REVIEW

**Comment by leomcelroy** [comment]
This is a very intricate piece! Could you parameterize it in some ways? Make it so you can adjust the minion using variables.

**Comment by celloii** [comment]
I uploaded an updated version of my index.js with adjustable variables. Thank you for your time!

**Comment by leomcelroy** [comment]
Thanks for updating your piece. Try to use the `setDocDimensions` and center your drawing in there. Right now I can't find it.

Also you folders are a bit messed up. Make sure you don't use spaces in the names and delete the old submission folder.

Keep at it!

**Review by maxwofford — CHANGES_REQUESTED** [review]
giphy-ezgif com-webp-to-gif-converter


Nice work! Make sure to also [rename your PR to the name of your folder](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#2-make-a-pr-with-your-original-artwork)!

Love that you have it changing direction too. What if you also have some that have different types of eyes & goggles

Minions_characters

**Comment by maxwofford** [comment]
Hey @celloii, any updates on mixing up the art a little bit more?

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in ~3 weeks, I will be closing this PR for now. Feel free to make a new PR with an updated submission in the future!

**Pull request closed without merging**
