### PR TITLE
SunsetAtSea-Irtaza

### PR DESCRIPTION
**Pull request by Irtaza2009**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here: 
- [x] Optional, if you remixed this from something else, mention it here: I got the idea for the birds from [this blot art in the gallery](https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/Mountain-EuanRipper/index.js)

## Sunset At Sea
I created a Sunset scene at the sea with some sailboats and randomly placed birds. It was my first time using a drawing library and drawing using a programming language, thus I wrote the code using the **.Turtle()** function, which I understood the most easily.

Here is an image of what my code can generate: 
image-1

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Nice job! Its really calming to look at, I really like the color pallet!
Some things that could elevate this piece even more:

- Make sure the birds don't collide
- Same with the boats
- I'd really to see different levels of the sunset. Randomize the height of the sun a little more, and make it dip below the horizon sometimes!
image

**Comment by Irtaza2009** [comment]
I have added all of your recommendations! I hope it looks better now!

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Nice job! Sometimes the sun goes out of frame on the top, do you think you could fix that?

**Comment by Irtaza2009** [comment]
I fixed it!

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is quite aesthetic! Nice work.

Keep in mind though the blot is going to draw in 1 color & have no fill, so the art ends up kinda sparse & janky with overlaps.
 
Screenshot 2024-08-02 at 11 23 19

Could you tweak it a bit more to make it work well on blot? Also maybe you can add more details to the boats or add in some water ripples. OOOoh! Or maybe it could rarely generate a whale breaching!

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in over a month, I'm going to close the PR for now. You're free to make a new one in the future with the same artwork if you'd like! Reach out to me @ alexren on the slack if you have any questions!

**Pull request closed without merging**
