### PR TITLE
feat: scanning pr for review - github action

### LINKED ISSUE #692: GH Action: Give users tips on changes they need to make
We implemented this on https://github.com/hackclub/onboard (for example: https://github.com/hackclub/OnBoard/pull/779#issuecomment-2209387096) & found our review times dropped by about 75%!

For blot, I think the big things to test are in [here](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#2-make-a-pr-with-your-original-artwork). Reiterating them in this issue (though the list might be out of date as the documents are updated)
- has a `art/ARTWORKNAME/index.js` file
- index.js [has metadata](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#20-add-metadata-to-your-indexjs-file)
- the ARTWORKNAME follows the right [format](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#22-place-your-program-in-a-folder-with-at-least-3-snapshots)
- the artwork has at least 3 snapshots in `art/ARTWORKNAME/snapshots/`

### PR DESCRIPTION
**Pull request by yednapg**
partially fix #692

### CODE REVIEW

**Comment by BrightTheBackpack** [comment]
do you think u could remove the test art before i merge this? Its gonna show up in the gallery if not removed

**Comment by yednapg** [comment]
done!

**Comment by BrightTheBackpack** [comment]
I'll merge this so we can try it out

**Comment by maxwofford** [comment]
Seems like this might not be working in prod! I haven't seen any messages come up. @yednapg, any clue what's up?

**Comment by BrightTheBackpack** [comment]
He said it was failing because it didn't have the permissions to comment

**Pull request merged**
