### PR TITLE
echograph--mattehwweinberger

### PR DESCRIPTION
**Pull request by ruckusmattster**
- [ ✔️ ] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [✔️  ] I am submitting art that...
  - [ ✔️ ] is algorithmically generated (will change each time the program is run)
  - [ ✔️ ] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [ ✔️ ] is original (not copied from somewhere else)
  - [ ✔️ ] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

i submitted something rubbish earlier today - then called my brother who is a really good coder and had him teach me properly. until now ive never coded. he helped me when i got stuck but for the most part this is all mine. hopefully its suitable

the art is a randomly generated graph with smoothing and added jaggedness, it has a "echo" of the graph trailing it with the density reflecting the gradient of the graph. this was a fun challenge to my math abilities. ive included one image showing another implementation of my gradient based variable shading and the true version (B&W)

graph2

image

### CODE REVIEW

**Comment by ruckusmattster** [comment]
please view the graph on a white background as the black lines arent very visible on dark mode github

**Comment by ruckusmattster** [comment]
forgot the image file extension in the meta data
also been reviewing other PR's, i see some generate something new for every run whereas ive used a seed to make the output repeatable. let me know if i need to make it truly different each generation - i can maybe figure out how to have a toggle to randomise all numbers

**Comment by ruckusmattster** [comment]
sorry im not sure why its failing - lmk if theres anything i can do to fix it

**Comment by ruckusmattster** [comment]
i tried making the graph user defineable but its not working right and i dont know why 
image
image

[project (4).txt](https://github.com/user-attachments/files/16566508/project.4.txt)

**Review by qcoral — CHANGES_REQUESTED** [review]
The math involved in this demo is really cool. With that though, I think you could definitely take this concept further and make it look even better. You have a really strong base, keep working at it!

**Comment by ruckusmattster** [comment]
Hey @qcoral what sort of changes would you like to see? I'm not sure how to push further other than add colour. I'm not the most artistic

**Comment by qcoral** [comment]
Currently, the art piece is very algorithmic & math heavy and doesn't have much artistic intent and/or interactivity. Could you try and change your art piece to be more than a graph plotter?

**Comment by Dongathan-Jong** [comment]
Hey there! I am closing this PR due to inactivity, please create a new PR once you have updated your art!

**Pull request closed without merging**
