### PR TITLE
Youtube_Plaque-Altyn 

### PR DESCRIPTION
**Pull request by BedlessApple**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

My blot project is my YouTube channel on a plaque that changes the number of subscribers that I passed and there is a 
a snake on top of my plaque that moves whenever I run the code there is also a small plant to the side of my plaque.
I put a logo on the plaque to.

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on color to look good

Lastly, link a picture of your art piece here:
image (4)

### CODE REVIEW

**Comment by BedlessApple** [comment]
when will it get authorized

**Comment by Dongathan-Jong** [comment]
Hey there! Don't worry about the Vercel deployment, it is for us. As for your art, this is a good start! Unfortunately, it falls under the bar as an approved piece. Please check out our submission guidelines found on the blot website. Once you have updated your art, I am happy to re-review it for you!

**Comment by BedlessApple** [comment]
Thank you, I will do that.

**Comment by M0HID** [comment]
Hi there! I’m closing this PR for now to clear up the repo. Once you’ve finished making your edits/improvements, please make a new PR and we can review it there!!

**Pull request closed without merging**
