### PR TITLE
WinterWonderland - Shayan

### PR DESCRIPTION
**Pull request by Shayan-Mazahir**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!
My artworks shows a snowy day near Christmas where it is snowing, a snowman is standing along a tree decorated with lights and a star! Working on this was a bit of experience, i had some issues in aligning the star on "top" of the tree, it took me a while which in the end lead me to use my "mathing" skills to set the variables properly. Overall, it was a nice experience and i would definitely do it again from scratch sometime! 
_ps i nearly decided to give up on the star, but my last try was successful_

Next, make sure you go through **each item** in the following checklist. Delete this line after!

- [✅] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [✅ ] I am submitting art that...
  - [ ]✅ is algorithmically generated (will meaningfully change each time the program is run)
  - [ ✅] is your own work that is not copied from somewhere else
  - [ ✅] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [ ✅] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [ ✅] Doesn't overlap lines more than 5 times
    - [ ✅] Fits in the working area of 125x125mm
    - [ ✅] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
image1

### CODE REVIEW

**Comment by Ssmidge** [comment]
Hey! The snowflakes seem to collide with eachother, and it doesn't currently look aesthetically pleasing with all of the collisions. Can you work on this a bit more? I'd love to see what you can come up with!

**Comment by Shayan-Mazahir** [comment]
> Hey! The snowflakes seem to collide with eachother, and it doesn't currently look aesthetically pleasing with all of the collisions. Can you work on this a bit more? I'd love to see what you can come up with!

Hey, i have updated the code with what u said; and have added some tress as well _(mainly cause i was bored)_

**Comment by Ssmidge** [comment]
I see that there are less collisions now, however some lines just appear, without being attached to anything, do you think you could improve on this a bit? Usually the question is: "Would you hang this up on a wall?"

This is a great improvement, but I'd love to see what you can come up with!

chrome_zp63ppNFh5

**Comment by Shayan-Mazahir** [comment]
> I see that there are less collisions now, however some lines just appear, without being attached to anything, do you think you could improve on this a bit? Usually the question is: "Would you hang this up on a wall?"
> 
> This is a great improvement, but I'd love to see what you can come up with!
> 
> chrome_zp63ppNFh5

those aren't lines... i left them there intentionally as they are representing that the snow flakes are going behind the snow man and the tress... i was aiming to to be a bit... "realistic".. but i can definitely try to improve it more

**Comment by Shayan-Mazahir** [comment]
> I see that there are less collisions now, however some lines just appear, without being attached to anything, do you think you could improve on this a bit? Usually the question is: "Would you hang this up on a wall?"
> 
> This is a great improvement, but I'd love to see what you can come up with!
> 
> chrome_zp63ppNFh5

Updated the code, hopefully its fine now!

**Comment by Dongathan-Jong** [comment]
Hey there! Going to jump in here. You've got a great start! Unfortunately, this falls short of our submission guidelines (due to simplicity). Currently only the snowflakes are random, do you think you could make the snowman + trees random? 

Also, the design should have zero colour in it as stated in the PR form: "Doesn't rely on colour to look good". Could you create a variable to disable colours? Lastly, the snowflakes seem to generate outside of the 125x125 workspace, please fix these once you get to them! :)
image

**Comment by Shayan-Mazahir** [comment]
> Hey there! Going to jump in here. You've got a great start! Unfortunately, this falls short of our submission guidelines (due to simplicity). Currently only the snowflakes are random, do you think you could make the snowman + trees random?
> 
> Also, the design should have zero colour in it as stated in the PR form: "Doesn't rely on colour to look good". Could you create a variable to disable colours? Lastly, the snowflakes seem to generate outside of the 125x125 workspace, please fix these once you get to them! :) image

just for the info, the snowfalkes **are not** the only things random, the lights on the tress are also random, but ill try to make the snowman as well... the color variables are on the top already... though ill make them the first variable on the code and will work on the rest

**Comment by Dongathan-Jong** [comment]
Hey, keep working at it! Just an update, I will be closing this PR. Please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Pull request closed without merging**
