### PR TITLE
DragonBall-Mayank

### PR DESCRIPTION
**Pull request by innovativecreations**
I grew up watching Dragon Ball, I usually go to my relative house on weekends to watch DragonBall with my cousin late at night. The whole moment is freshly engraved into my mind like it was yesterday.
In this project, I've tried to build a script for Blot to draw Dragon Ball. 

4 stars Dragon Ball

Although it's my 4/5 PR(don't remember the exact number), I'm positive this will be my last.

### CODE REVIEW

**Comment by BrightTheBackpack** [comment]
This looks pretty cool! I'm going to tentatively approve this.

**Review by BrightTheBackpack — APPROVED** [review]
This looks pretty cool! I'm going to tentatively approve this.

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is a good start, but I don't think we can accept this just yet. The generative art here is just an if statement to choose between a couple pre-programmed things. The intent for this is that the art and beauty of your piece comes out of the generative aspect of it. Currently the dragonball looks good but it's good because you hard-coded it

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in 4 weeks, I will be closing this PR for now. Feel free to make a new PR with an updated submission in the future!

**Pull request closed without merging**
