### PR TITLE
Boba-BuubleTeaDreams

### PR DESCRIPTION
**Pull request by CodingMasterGirl**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

Next, make sure you go through **each item** in the following checklist. Delete this line after!

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:

### CODE REVIEW

**Comment by EnterpriseGoose** [comment]
Hello! I'm excited to see your submission. Could you please follow the instructions [here](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md) for how to submit your files so I can review your project? Thanks!

**Review by CodingMasterGirl — COMMENTED** [review]
[snapshots.zip](https://github.com/user-attachments/files/17852760/snapshots.zip)
[index.zip](https://github.com/user-attachments/files/17852761/index.zip)

**Comment by CodingMasterGirl** [comment]
My art work was really fun when I drawed it, I loved how it a creative idea that I got out of nowhere...

**Comment by EnterpriseGoose** [comment]
I am very excited to see it, but I still need you to make your files in the format shown by the link I gave you above. If it's easier, you can close this pr and make a new one in that format. Without making it in that format, I cannot view your files.

**Comment by CodingMasterGirl** [comment]
How do I do that? Can you help me out?

**Comment by CodingMasterGirl** [comment]
I've been trying forever but it keep giving me this message...

**Pull request closed without merging**
