### PR TITLE
Car Riding Off Into The Sunset - Daksh

### PR DESCRIPTION
**Pull request by DakshRocks21**
I present to you, a scuffed f1 inspired car. The grass/wheels/sun and spoiler are randomly done.
I had a lot of fun building this. :D

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
I love the scene in this art piece! While it looks great in the editor, it unfortunately is not drawable by Blot due to the heavy use of fill. Can you make it still look good with only single-color lines?

**Comment by DakshRocks21** [comment]
will do. give me some time

**Comment by DakshRocks21** [comment]
@qcoral, updated the design.. removed colours :D

**Comment by Dongathan-Jong** [comment]
This could use some more work! I would like to see more put in the art, different car sizes, different landscapes, etc. Also, some grass seems to be generating outside of the border! Please create a new PR once you have updated your art. I closing this due to a new management system for the PRs.

**Pull request closed without merging**
