### PR TITLE
run_and_get_random_art-abhay

### PR DESCRIPTION
**Pull request by uniquepersun**
- [x ] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x ] I am submitting art that generates random circles and make art out of it, it changes based on time and also it'll change each time it runs sothat you can't get the same art again!!
  - [x ] is algorithmically generated (will change each time the program is run)
  - [x ] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x ] is original (not copied from somewhere else)
  - [x ] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Comment by uniquepersun** [comment]
@maxwofford 
Is this program closed?? Or they'll be reviewed after any specific date/criteria. Sorry for pinging

**Comment by uniquepersun** [comment]
Heyyy, don't merge this pr or review it as I'm now working for blot ao making some more thing..

**Comment by uniquepersun** [comment]
Heyyy, don't merge this pr or review it as I'm now working for blot ao making some more thing..

**Comment by uniquepersun** [comment]
nvm just review it I'll make another commit for another art as I also want to save this code too!

**Comment by M0HID** [comment]
Hi, this is an awesome start to your project! However, it is a bit too simple to be eligible for a Blot. Could you continue working on this? Update me when you’re done and I’ll review it again.
(Also `bt.rand` does not take any parameters, so you might wanna remove that bit)

**Comment by uniquepersun** [comment]
ohh, okay thanks will update this

**Comment by Dongathan-Jong** [comment]
Keep working at this! Please create a new PR once you have updated your art, keep working at it! I am doing this due to a new management system for PRs.

**Comment by uniquepersun** [comment]
okayy got it, thankssss.
I'll prolly make it this weekend...

**Pull request closed without merging**
