### PR TITLE
Galaxy--Nikhil

### PR DESCRIPTION
**Pull request by Nikhil8557**
It's a dance of starlight, a constellation caught mid-waltz. The negative space whispers of endless possibility, the inky void between the **stars** a canvas for dreams. Each point of light, a tiny dancer, spins and twirls, leaving a trail of stardust in its wake. Their simple form, a stark contrast to the swirling **energy** they embody. Is it a glimpse into a **newborn** galaxy, or a memory of a  forgotten one? Perhaps it's a question whispered on the wind, a silent symphony played out in the **language** of the cosmos.
Galactic

I **loved** coding it, learning blot was fun. I hope I can teach it to others. And magic happens when we write code and **drawing** is already there.

### CODE REVIEW

**Review by Nikhil8557 — COMMENTED** [review]
Inspired By Starry Nights
~Van Gough
image

**Comment by leomcelroy** [comment]
I think this composition is a bit haphazard. I shared some feedback on Slack already. I think you should focus on getting the spiral effect from the distribution of stars.

**Comment by Nikhil8557** [comment]
Hey, @leomcelroy can you add more

**Comment by leomcelroy** [comment]
Since we've discussed in DMs I'm going to close this PR.

**Pull request closed without merging**
