### PR TITLE
sunrise-ram

### PR DESCRIPTION
**Pull request by Selven11**
This is a piece called sunrise where the mountains and birds change every time it is run. My inspiration came from the fact that I've seen so many drawings of sunrises, yet they all look distinctly unique and different. 

My first ever time working with blot, it was really confusing at first and I had no clue what I was doing, And I had so many, many, issues when trying to make the randomizer from the birds and it took a lot of time to figure out how it works.

Overall, I really liked being exposed to blot and it helps with my understanding of art through programming.
snapshot1

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
This is a pretty good start! I really like the mountains you added
I feel like there could be a couple small improvements, like making the birds that are behind the clouds disappear, and also making the mountain have a generative shape that changes a little every time!

**Comment by BrightTheBackpack** [comment]
this piece seems to be a derived from [this](https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/DesertSunset-Augustin/index.js). Anyway you can add more things to make it your own?

**Comment by maxwofford** [comment]
Bump on this, @Selven11– do you have another pass on this art?

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey! I really like the overall vision you're going for here. One thing I want to mention is that because of the heavy use of colour, when it's actually drawn on Blot, it'll look like this:
image

Could you try and make it less color-reliant? I'm excited to see what you come up with!

**Comment by Dongathan-Jong** [comment]
Closing this PR due to inactivity! Please create a new PR when you update your art!

**Pull request closed without merging**
