### PR TITLE
Starry Sky By Le_honk

### PR DESCRIPTION
**Pull request by le-honk1**
This is my first time using JavaScript and It was a fun project that I'm glad I did 
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
This looks pretty cool! Do you think you could make the trees at random heights?

**Comment by maxwofford** [comment]
@le-honk1, just checking in if you have updates on your art

**Comment by le-honk1** [comment]
Hi, I’m sure I can figure out how to make the trees different heights as well! Sorry for the late response haha

**Comment by maxwofford** [comment]
@le-honk1 np! I'm excited to see what you come up with. If you need help with either github or coding blot you can hop in the slack to chat with other people using both!

**Comment by le-honk1** [comment]
Thank you, I appreciate the help, I joined the slack but haven’t made much use of it, so I certainly will!

**Comment by qcoral** [comment]
@le-honk1 any update on this?

**Comment by Dongathan-Jong** [comment]
Hey! I am closing this PR due to inactivity! Please create a new PR once you have updated your art!

**Pull request closed without merging**
