### PR TITLE
HeartOfCircles

### PR DESCRIPTION
**Pull request by PawiX25**
- [X] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [X] I am submitting art that...
  - [X] is algorithmically generated (will change each time the program is run)
  - [X] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [X] is original (not copied from somewhere else)
  - [X] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [X] is drawable on a physical machine (doesn't have lines overlap more than 5 times)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
This is a really cool piece, and it's pretty close to being merged! I just ask that the scene has a bit more detail. I'll come back later!

**Comment by PawiX25** [comment]
Thank you for the feedback! I’ve added more detail to the scene by introducing a background pattern with varied shapes, including circles, ellipses, and polygons. Looking forward to your thoughts on these updates!

**Comment by PawiX25** [comment]
Hey @qcoral! I’ve made the changes you requested, including heart detection, transformations, and tweaks to avoid overlap. I also added some extra elements like circles, ellipses, and spirals. Let me know if there's anything else! Thanks for your feedback—it really shaped the piece!

**Comment by Dongathan-Jong** [comment]
Neat update! Just a small flaw, circles will generate outside of the border, and the blot cannot draw that. Once you fix that, please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Comment by PawiX25** [comment]
I've fixed it here: https://github.com/hackclub/blot/pull/946

Let me know if you have any other questions

**Pull request closed without merging**
