### PR TITLE
SteamyHotMug-KrishivaMatta

### PR DESCRIPTION
**Pull request by ItsDaraaa**
My artwork, as said in the name, is a steamy hot mug; what makes is steamy is the fact that there are random values to the steam drawing to make it look like a real time steaming hot mug on every run. The steam moves! Before today, I had no clue on how javascript works. It took me a long time to actually learn and execute commands. The video and instructions provided helped me understand it better and to eventually making my very first artwork I made with plain code. At the moment, this is the only bit of javascript I know, and I am sure it will improve over time in order for me to make better art!

- [Y ] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [ Y] I am submitting art that...
  - [Y ] is algorithmically generated (will change each time the program is run)
  - [ Y] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [ Y] is original (not copied from somewhere else)
  - [ Y] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
This is creative! I like the clear vision with the image, but it's a little simple. Could you work on this more?

**Review by ItsDaraaa — COMMENTED** [review]
I updated it, is there anything else I could do or is this good?

**Comment by ItsDaraaa** [comment]
> This is creative! I like the clear vision with the image, but it's a little simple. Could you work on this more?

Of course!, I just added more, is there anything else or is this good?

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey, I like the new changes you added but this is still very far off the mark. You can find submission guidelines here:
https://blot.hackclub.com/submitting

**Comment by Dongathan-Jong** [comment]
Hey there! I am closing this PR due to inactivity, please create a new PR once you have updated your art!

**Pull request closed without merging**
