### PR TITLE
DynamicEmoji-Anuradha

### PR DESCRIPTION
**Pull request by anuradha-lakruwan**
I created my first blot art to show an emoji face.it can show 4 basic emotions.Happy,Sad,Angry and Surpirsed.Also you can make the emoji a hairless bold guy or make it full with haair.the choice is yours.feel free to change the each line for each emotion to make your own customized emoji.I am really happy about this as this is my first blot art and I learned a lot designing this.I tried to make a emoji girl,but the shapes were not good.so chose the round face.in my next step i am developing a emoji girl

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here: Nothing

Lastly, link a picture of your art piece here:

### CODE REVIEW

**Comment by M0HID** [comment]
Hi! Great start to your project, but currently it is not algorithmically generated. (It needs to be different every time i run the program). Could you fix that and then update the PR please?

**Comment by anuradha-lakruwan** [comment]
> Hi! Great start to your project, but currently it is not algorithmically generated. (It needs to be different every time i run the program). Could you fix that and then update the PR please?

sure i will look into this.So you mean everytime when we run the programme,it must change the emoji right? I have set variables for that.so i need to update them everytime when i run it right?

**Comment by anuradha-lakruwan** [comment]
sure i will look into this.So you mean everytime when we run the
programme,it must change the emoji right? I have set variables for that.so
i need to update them everytime when i run it right?

**Review by qcoral — CHANGES_REQUESTED** [review]
hey - great start, but this needs a lot more work to for a blot. maybe try making the emoji girl!

**Comment by anuradha-lakruwan** [comment]
@qcoral I have changed the project to something more complex. Please check it .I came across with this project idea when I try to create the hair for the emoji girl 😅 Thank you for the suggestion !🥰

**Comment by qcoral** [comment]
hey - could you make a new PR for this? it's a new piece

**Comment by anuradha-lakruwan** [comment]
@qcoral sure i will create new one and let you know

**Pull request closed without merging**
