### PR TITLE
{among us}--{Sahil Dasari}

### PR DESCRIPTION
**Pull request by sahilchess**
I started coding when I was about 10 in my 5th grade. It interested me when I saw my sister code something. I saw so many lines of code and then, at an instant, I saw a calculator, or a flower drawing etc. She is my inspiration behind starting to code. 

My drawing is an Among us impostor
I could add a marker instead of a pen and color in the drawing. (
Red for body and bag
Light blue for glasses
)

My impostor took about 4- 5 hours because I was a little new to the blot interface because it is a little different from python turtle. I also ran into many bugs, so taking inspiration from my sister, I explained everything to a rubber duck and quickly found the issues

### CODE REVIEW

**Comment by V205Arduino** [comment]
Seems cool!

**Comment by alx-alexpark** [comment]
sussy

This is truly amazing.

**Comment by sahilchess** [comment]
Screenshot 2024-02-04 2 10 46 PM

I forgot to add 3 screenshots so here is my 3rd one.
Big Head and Big Right Leg, changed 3 parameters

**Comment by leomcelroy** [comment]
It's a simple drawing but you captured the essence well. Nice work, you've earned your Blot.

[You can order it here if you're a teen.](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
