### PR TITLE
Bus-Potatoes

### PR DESCRIPTION
**Pull request by agentdog**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Good start! I really like the randomization you've added!
It would be cool if there was a door, and a little divot where the wheels are, similar to this drawing i found:
image
I also think it would be cool if it was on a road, with background stuff, like this:
image

**Comment by maxwofford** [comment]
Hey @agentdog, just checking in– any updates on how your art looks?

**Comment by agentdog** [comment]
hey sorry this notification somehow got muted out, currently working on the changes

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in over 2 weeks, I'm going to close the PR for now. You're free to make a new one in the future with the same artwork if you'd like! Reach out to me @alexren on the slack if you have any questions!

**Pull request closed without merging**
