### PR TITLE
Cedar Tree - Reese Ochitwa

### PR DESCRIPTION
**Pull request by ReeseOchitwa**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

My drawing is a forest consisting of three rows of cedar trees. The cedar tree is the symbol of the Lebanese flag and the national tree. The tree symbolizes strength and resilience in Lebanon. The algorithmic part of my code generates a unique number of trees per row each time which constrains to the dimensions of the drawing surface.  The forest can be drawn in colour including a yellow sun,  blue sky, and brown ground, with randomized green trees or in black and white with a white sun and white trees.

- [ x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x ] I am submitting art that...
  - [x ] is algorithmically generated (will meaningfully change each time the program is run)
  - [ x] is your own work that is not copied from somewhere else
  - [ x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x ] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x ] Doesn't overlap lines more than 5 times
    - [x ] Fits in the working area of 125x125mm
    - [ x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
[art/cedarForest-ReeseOchitwa/snapshots/cedarForest.png 
](https://raw.githubusercontent.com/ReeseOchitwa/blot/main/art/cedarForest-ReeseOchitwa/snapshots/cedarForest.png)

### CODE REVIEW

**Comment by ReeseOchitwa** [comment]
I added a more algorithmic element to the design. Each time the code is run, it generates a grid of trees that constrain to the width and height of the drawing surface based the x,y scale of the tree that also changes on each iteration.

**Comment by Ssmidge** [comment]
Hey! This is better, but I still think you could work on it to make it _perfect_! You should try to make it into a forest, or maybe even an entire landscape! I think you have a lot of potential with this as a foundation for a beautiful project

**Comment by ReeseOchitwa** [comment]
Thanks for your input and helping me to improve my project. I used the row concept to create three rows of randomized scales. I also played around with colour. Although I do use color, I included comments to explain how to create a black and white drawing, so the forest doesn't rely on color. I also made the scales proportional so the trees don't become morphed. 
Thanks again!

**Comment by Ssmidge** [comment]
This is a lot better! I really like the customizability of the colors, could you rename the JS file to `index.js` though? I have sent it to alex, it might take a couple days for it to be reviewed though (longer weekend :D)

**Comment by ReeseOchitwa** [comment]
updated :)

**Comment by Ssmidge** [comment]
Hey! Sorry for the delay, could you add a global variable (ie at the top of the file) to toggle colours? It's about the only remaining thing!

**Comment by ReeseOchitwa** [comment]
Added!

**Comment by Dongathan-Jong** [comment]
Neat art! As of now, this pieces falls short of the bar due to simplicity! I would recommend making each tree different, instead of just changing the size. Please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey - awesome changes, this is super close! I think the image could be more generative though, i.e the patterns on the trees changing

**Pull request closed without merging**
