### PR TITLE
Add dark mode to the editor

### LINKED ISSUE #194: Dark mode or customizable pallette
Know this seems extravagant, but I find I'm most creative at night and really want to use blot on a dark screen.

I'm 100% ok with not having official support for dark mode; but currently the way the turtle is rendered, extensions like "dark reader" will black out the canvas entirely:

Screenshot 2023-12-01 at 12 59 39

Short of a full dark-mode, I'd like the ability just to change the color of the pen in the renderer to work with the extension.

### PR DESCRIPTION
**Pull request by BrightTheBackpack**
Added dark mode to the editor, console, and preview. I'm not doing the help section yet, because i want to wait till it gets fixed. 

close #194

### CODE REVIEW

**Comment by BrightTheBackpack** [comment]
Don't Merge yet I wanna make a couple changes

**Comment by BrightTheBackpack** [comment]
all done

**Comment by BrightTheBackpack** [comment]
sorry bout all the commits btw. I'm on my laptop so i needed to use a vercel deployment to see my changes

**Comment by leomcelroy** [comment]
Thanks so much for this. I'll take a look to review.

**Comment by leomcelroy** [comment]
Okay back from the holiday! Very grateful you took a look at this. It seems that the help section doesn't render properly. 

It had a similar effect when I ran just this branch so I pushed some upstream changes we added to the markdown parser that I thought may fix it and we still see the same white area (though perhaps for different reasons). 

Screenshot 2024-01-03 at 2 29 54 PM

When that renders properly we can merge this in.

Another thought is perhaps the turtle lines and the outline should be a different color, as is the case in light mode.

**Comment by BrightTheBackpack** [comment]
this should fix the help section! I don't really understand what you mean by having the turtle lines and outline be a different color.

**Comment by BrightTheBackpack** [comment]
OHHH i got it. I was messing around with the colors on my local repo, so the frame was black. I'll work on making the outline and pen colors different

**Comment by maxwofford** [comment]
@BrightTheBackpack this PR theme looks slick! Def will be my default use of the editor once this gets merged. What else needs to happen to get this brought in?

**Comment by BrightTheBackpack** [comment]
Just gotta fix the outline color and resolve conflicts. I'll get started when I get home in about 2 hours

**Comment by BrightTheBackpack** [comment]
I'm closing this and i'm gonna start a new pr

**Pull request closed without merging**
