### PR TITLE
LissajousCurve-Pratyush

### PR DESCRIPTION
**Pull request by Pradevel**
It makes cool art using the Lissajous curve function. (Its randomized every time)

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] doesn't call Math.random() (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
snapshot1

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
I like this! I've never heard of these curves before, so I definitely learned something new with this PR. I think you can take this concept even further through even _crazier_ math (or something else!), so keep working at it! I'll come back soon

**Comment by Pradevel** [comment]
@qcoral  Honestly, I don't know what I changed but seems like we have two curves now making a quite interesting output. I'll update the pics too soon. (updated)
PS: There is a `TILT` variable which allows you to play with the design. You can try sliding the value for some interesting outputs. 

Screenshot 2024-08-19 at 9 02 31 PM

**Comment by Pradevel** [comment]
@qcoral I changed from drawing lines to drawing squares of varying sizes. I updated the pics as well. 
snapshot1

**Comment by Dongathan-Jong** [comment]
Super cool! I think this could use some more work, maybe different shapes? Please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Pull request closed without merging**
