### PR TITLE
Mushroom-Nithin

### PR DESCRIPTION
**Pull request by NitWit-28**
The art piece I drew is a mushroom generated randomly in a grid of lines. My inspiration came from a mushroom toy in my room which I decided to draw!

My experience with blot was very interesting and fun it gave me a lot of insight into programming and it was just a fun and good learning experience.

I hope to get my robot soon!

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Love the lighting effect you have on the canvas! Just a couple suggestions:

I'm having a bit of trouble picturing the mushroom, could you maybe create it so it looks something more mushroom-like? 

Also, the shading on the image does get pretty dark, and there are some concerns about if the blot could or couldnt draw this. I would suggest making the shading a bit brighter. 

Just to be clear, these are just suggestions and you are free to do whatever your heart contents.

**Comment by Dongathan-Jong** [comment]
Unfortunately, this submission falls short, but you're off to a great start! You don't need to create a brand new one, you can just build off of your current submission.

**Comment by NitWit-28** [comment]
> Unfortunately, this submission falls short, but you're off to a great start! You don't need to create a brand new one, you can just build off of your current submission.
how can I submit a new one ?

**Comment by Dongathan-Jong** [comment]
I will be closing this PR due to inactivity! Please create a new PR when you have updated something.

**Pull request closed without merging**
