### PR TITLE
faithLoveHope-opensource25

### PR DESCRIPTION
**Pull request by opensource25**
The Artwork shows the Faith-Love-Hope Symbol in various color combinations. It was a hard but fun journey coding it in the school free time, especially with little experience with JS, even less with the blot specific parts. Also, I'm not the very good artist.
snapshot1

- [ x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x ] I am submitting art that...
  - [x ] is algorithmically generated (will change each time the program is run)
  - [ x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [ x] is original (not copied from somewhere else)
  - [ x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [x ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [x ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Hi there! This looks pretty cool!
However, it doesn't really meet the [generative requirement](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md). Can you think of a way to make it more generative, and have changes other than just the colors?

**Comment by maxwofford** [comment]
How's it going @opensource25? Do you have an updated version of the art?

**Comment by opensource25** [comment]
To make it more generative I thought of generating a different background each time it runs. But sadly hadn't had any time coding the last week.

**Comment by opensource25** [comment]
I finally was able to code the new background. What is the proper way to submit it? Is there a way to update this PR, or do I need to create a new PR and close this?

**Review by qcoral — CHANGES_REQUESTED** [review]
This is a really pretty design! Could you add a variable at the top that disables all the color so I could see what it looks like when it's drawn on Blot?

**Comment by Dongathan-Jong** [comment]
I tried making that variable false, and making the above variable black, but am running into an error, please fix! Create a new PR once you have updated your art, keep working at it! I am doing this due to a new management system for PRs.

**Pull request closed without merging**
