### PR TITLE
aFractalForayIntoTheForest-Adya

### PR DESCRIPTION
**Pull request by AdyaS2010**
- [x] I have read the steps to getting a blot, had fun programming the artwork (I had to take a little time to adjust to the environment though). 
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] calls `bt.randInRange`

- [x] I did get inspiration (of the idea to create a tree made of fractals) in the real world. 
FractalTree -> This image is not correct, check files for latest please. 
- [x]

### CODE REVIEW

**Comment by BrightTheBackpack** [comment]
Hey there! Make sure all your snapshots are in a /spapshots/ folder, and rename your js file to index.js! Also make sure aren't using Math.random()

**Comment by AdyaS2010** [comment]
> Hey there! Make sure all your snapshots are in a /spapshots/ folder, and rename your js file to index.js! Also make sure aren't using Math.random()

Got it. Renamed file to index.js and adjusted code to function as desired without using Math.random(). 
Could you please tell me how to create a folder, and add my other files outside of the art folder into it?

**Comment by AdyaS2010** [comment]
> Hey there! Make sure all your snapshots are in a /spapshots/ folder, and rename your js file to index.js! Also make sure aren't using Math.random()

Got it. Done!
Could you please check again?

**Comment by BrightTheBackpack** [comment]
Now it doesn't seem to be different on every run. you can use bt.randInRange instead of math.random

**Comment by AdyaS2010** [comment]
Ok, done!

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is a good start @AdyaS2010, but I think you can go further! Keep in mind most accepted submissions take 15-20 hours of work.

**Comment by AdyaS2010** [comment]
> This is a good start @AdyaS2010, but I think you can go further! Keep in mind most accepted submissions take 15-20 hours of work.

Should I expand on top of the existing model and experiment with new ideas, or restart the whole thing?

**Comment by AdyaS2010** [comment]
@BrightTheBackpack @maxwofford (sry for the ping) I have updated my Project after spending a lot more time on it; had a lot of fun, learnt so much, and am proud of my work! Thank you guys so much for putting this together and providing such opportunities!

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey! This art piece is great, but a lot of it is static.Could you add some more generative/varied elements?

**Comment by BrightTheBackpack** [comment]
Also make sure all your files are in a folder with your art name, and your name!

**Comment by AdyaS2010** [comment]
> Also make sure all your files are in a folder with your art name, and your name!

Done!!! Is the artwork piece all good now?

**Comment by Dongathan-Jong** [comment]
Great updates! This is pretty close to getting a blot! Just a few things before though, currently the canvas size is not 125x125, and needs to be that, so please scale your art down! Also, I'd like to see a little more generation of the ground. With that done, please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Pull request closed without merging**
