### PR TITLE
Sudoku Game Drawer - Yash Vardhan Niranjan

### PR DESCRIPTION
**Pull request by Yash00241**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

Next, make sure you go through **each item** in the following checklist. Delete this line after!

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey there! This is so cool! I love how they're all solvable! I will forward this to Alex for next steps/approval. If needed, you may be asked to increase the complexity of your piece as per our submission guidelines!

**Review by qcoral — CHANGES_REQUESTED** [review]
This is a really clean implementation! A couple things:

1) Could you include some sort of description within your code explaining what it is // what it does?
2) I think some more flair around the game board would be great! Maybe adding a sudoku title or something?

**Comment by Yash00241** [comment]
> Hey there! This is so cool! I love how they're all solvable! I will forward this to Alex for next steps/approval. If needed, you may be asked to increase the complexity of your piece as per our submission guidelines!
> 
> Also, please change your PR name to Projectname-Yourname. For example: GameDrawer-Yash

Hey @Dongathan-Jong You asked me to change the name did it so.
Also a question was asked related to complexity of the game, so you can adjust the difficulty by changing the value of game difficulty in the code it is marked as **const difficulty** in the first few lines of the code.

Hope it helps  =D

Screenshot_10-9-2024_1817_github com

**Comment by Yash00241** [comment]
Got it and did it, completed all the given tasks :)

**Comment by BrightTheBackpack** [comment]
btw "If needed, you may be asked to increase the complexity of your piece as per our submission guidelines!" isn't talking about the game difficulty, just the complexity of the actual art piece

**Comment by Yash00241** [comment]
> btw "If needed, you may be asked to increase the complexity of your piece as per our submission guidelines!" isn't talking about the game difficulty, just the complexity of the actual art piece

Thanks @BrightTheBackpack I would surely add some more changes which I would be able to and make the art pieces more attractive and beautiful.

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey! You're almost there, if you could just add more visual flair to the piece (maybe a frame?? or something else), I think that would really help the piece

**Comment by Dongathan-Jong** [comment]
Just an update, I will be closing this PR! Please create a new PR once you have updated your art! We are doing this due to new management of the PR system.

**Pull request closed without merging**
