### PR TITLE
scenery_windmill-Riston

### PR DESCRIPTION
**Pull request by ristonrodrigues723**
inspired of scenery of mountainside windmills and flowerfields in the fields of netherlands,

### CODE REVIEW

**Comment by ristonrodrigues723** [comment]
@leomcelroy does it need any changes?

**Comment by leomcelroy** [comment]
Nice. I like the windmill a lot. I think you could clean up some of the overlapping lines a bit more. 

Interesting choice to depict the Netherlands with mountains.

The main issue is your submission structure is messed up. Can you make sure you have the right folders and file names. Ready through the submission guide carefully.

**Comment by ristonrodrigues723** [comment]
> Nice. I like the windmill a lot. I think you could clean up some of the overlapping lines a bit more.
> 
> Interesting choice to depict the Netherlands with mountains.
> 
> The main issue is your submission structure is messed up. Can you make sure you have the right folders and file names. Ready through the submission guide carefully.

ok will do it today itself

**Comment by ristonrodrigues723** [comment]
image
should his suffice for overlapping lines

**Comment by ristonrodrigues723** [comment]
> image should his suffice for overlapping lines

removed the lines inside the square

**Review by maxwofford — CHANGES_REQUESTED** [review]
This looks awesome @ristonrodrigues723! Just need you to fix the name of the PR (currently it says "Add files via upload", but the title should be your folder name), as well as add a couple more things to your scene. It's looking really great rn, but I think you can add a little more. Here are a couple ideas:

- the windmill seems to not pick it's pen up before moving so there are some crossed lines
- add a door or window that sometimes shows up on the windmill
- add a river that sometimes shows up
- sometimes show clouds

You don't have to implement all of them, but if you add some changes that'd help!

**Comment by maxwofford** [comment]
Hmmmm, this also [looks a little derivative](https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/Mountain-EuanRipper/index.js). You'll def have to show more generated stuff now if only the windmill is yours

**Comment by ristonrodrigues723** [comment]
> Hmmmm, this also [looks a little derivative](https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/Mountain-EuanRipper/index.js). You'll def have to show more generated stuff now if only the windmill is yours

@leomcelroy the flower garden is mine too

**Comment by ristonrodrigues723** [comment]
> This looks awesome @ristonrodrigues723! Just need you to fix the name of the PR (currently it says "Add files via upload", but the title should be your folder name), as well as add a couple more things to your scene. It's looking really great rn, but I think you can add a little more. Here are a couple ideas:
> 
> * the windmill seems to not pick it's pen up before moving so there are some crossed lines
> * add a door or window that sometimes shows up on the windmill
> * add a river that sometimes shows up
> * sometimes show clouds
> 
> You don't have to implement all of them, but if you add some changes that'd help!

 * sometimes show clouds tried that but the shapes arent drawing perfectly, and make up mess 
 *  add a river that sometimes shows up - csan be done , already tried but doesnt look good ,
 *

**Comment by maxwofford** [comment]
Update this PR with the new code once you're ready for me to review. It's 100% ok if you end up implementing features that are different than my suggestions– I just review on the review criteria & as part of that [I'm looking for](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#1-make-a-unique-piece-of-generative-art) some algorithemically generated art that looks nicely different everytime it generates

**Comment by ristonrodrigues723** [comment]
> Update this PR with the new code once you're ready for me to review. It's 100% ok if you end up implementing features that are different than my suggestions– I just review on the review criteria & as part of that [I'm looking for](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#1-make-a-unique-piece-of-generative-art) some algorithemically generated art that looks nicely different everytime it generates

@maxwofford dine with code upload u may check it

**Comment by maxwofford** [comment]
@ristonrodrigues723 I'm generating things but I don't see what changed! Can you give me a summary or post new pics in a comment for what it should look like?

**Comment by ristonrodrigues723** [comment]
@maxwofford the flowers are now being filled being filed with multiple  colors , insted of only black, or a single color at a time, the flowers, not being restricted to a single limited spsace as in first code,written code to fill the entire drawing with colors, removed the sun

**Comment by maxwofford** [comment]
If you need help editing the files in your PR, you should post in the #blot channel in slack! People there can help!

That share link might not be going to the right place, it looks the same as last time!

Screenshot 2024-07-15 at 17 37 08

**Comment by ristonrodrigues723** [comment]
> If you need help editing the files in your PR, you should post in the #blot channel in slack! People there can help!
> 
> That share link might not be going to the right place, it looks the same as last time!
> 
> Screenshot 2024-07-15 at 17 37 08

yep but isnt it a big improvement over,  can just check the code
image
i can add clouds and a sun with its phases and clouds  but it will liik cramped

**Comment by ristonrodrigues723** [comment]
> If you need help editing the files in your PR, you should post in the #blot channel in slack! People there can help!
> 
> That share link might not be going to the right place, it looks the same as last time!
> 
> Screenshot 2024-07-15 at 17 37 08

the prblm isthe code is updated on my local repo and not the in the pr

**Comment by ristonrodrigues723** [comment]
> > If you need help editing the files in your PR, you should post in the #blot channel in slack! People there can help!
> > That share link might not be going to the right place, it looks the same as last time!
> > Screenshot 2024-07-15 at 17 37 08
> 
> the prblm isthe code is updated on my local repo and not the in the pr

tried editing the file but not able too

**Comment by ristonrodrigues723** [comment]
image

**Comment by ristonrodrigues723** [comment]
> image

@maxwofford is this good bro,

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
I really like this!
The clouds look a little bit weird being titled and inverted in the middle.

**Comment by ristonrodrigues723** [comment]
> I really like this! The clouds look a little bit weird being titled and inverted in the middle.
yeah i just inverted the above one to draw the lower, can add a 3rd one to cover its tilt

**Comment by ristonrodrigues723** [comment]
@BrightTheBackpack https://blot.hackclub.com/editor?shareId=cc7cf7f9-f78a-4d02-9133-df134378dde1 the inversion is due to the the first cloud being copied and split in the middle
in this its fixed b adding another patch

**Comment by ristonrodrigues723** [comment]
the tilt was necessary to give the look of clouds on a side

**Comment by ristonrodrigues723** [comment]
> @maxwofford can u check it-https://blot.hackclub.com/editor?shareId=cc7cf7f9-f78a-4d02-9133-df134378dde1

@maxwofford

**Review by qcoral — CHANGES_REQUESTED** [review]
This art piece looks good so far, but it can't be drawn by Blot because it relies a ton on color. Can you make it look good using only lines?

**Comment by ristonrodrigues723** [comment]
> This art piece looks good so far, but it can't be drawn by Blot because it relies a ton on color & fill. Can you make it look good using only lines?

if i remove the color it wont look as good i can rem\ove the color as multiple lines drawn to fill in patterns inste of color will mess it up like it did initially

**Comment by ristonrodrigues723** [comment]
> > This art piece looks good so far, but it can't be drawn by Blot because it relies a ton on color & fill. Can you make it look good using only lines?
> 
> if i remove the color it wont look as good i can rem\ove the color as multiple lines drawn to fill in patterns inste of color will mess it up like it did initially

@qcoral if i remove colors ill have to add lines in the shapes to make it look beter and it would probablem mess everything up as it did initialy when i was recommended to to remove those

**Comment by ristonrodrigues723** [comment]
@qcoral would a plain drawing without the color suffice it wouldnt look that good for this

**Comment by EmperorNumerius** [comment]
Hi there!

I’m going to close this PR for now to clean up the repo. Once you've made your edits or improvements, please feel free to open a new PR, and we’ll be happy to review it there.

Please make sure to save your current code, and I'm looking forward to seeing your updated PR! Unfortunately, the color feature will need to be removed, but you might want to explore implementing a shading algorithm as an alternative—it could be a great addition!

Thanks again for your work!

**Pull request closed without merging**
