### PR TITLE
SinBall-Hrushal

### PR DESCRIPTION
**Pull request by Hrushal-Nikhare**
- [x ] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [ x] I am submitting art that...
  - [x ] is algorithmically generated (will change each time the program is run)
  - [x ] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x ] is original (not copied from somewhere else)
  - [x ] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x ] is drawable on a physical machine (doesn't have lines overlap more than 5 times)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
This is pretty cool, but is VERY slow to run - can you do some optimization?

**Comment by Hrushal-Nikhare** [comment]
Sure ill try if possible

**Comment by Hrushal-Nikhare** [comment]
it takes 5 seconds on my pc is that not fast enough?

**Comment by Hrushal-Nikhare** [comment]
Call to draw took 1838 milliseconds? thats pretty good tbh

**Comment by Hrushal-Nikhare** [comment]
Call to Cut  took 1765.5 milliseconds
Uh oh

**Comment by Hrushal-Nikhare** [comment]
synced repo and had to make a new pr:
https://github.com/hackclub/blot/pull/887

**Pull request closed without merging**
