### PR TITLE
sunflower-ofir

### PR DESCRIPTION
**Pull request by Ofish-Ofish**
Hello,
I wanted to make a flower for my drawing and one of my favorites is a sunflower so i decided to code it.
For the middle of the sunflower i used a spiraling pattern made of two functions who draw arcs in a circle in opposite direction.
For the pedal i used turtle to select 5 points on the outline of each leaf and use them to generate a curve.
Both the amount of pedals and the amount of arcs are chosen randomly from the Fibonacci sequence and the size of each also pedal changes randomly.
Most of my experience coding is in python.
I hope you like my drawing :) i had fun creating it.

sunflower1

### CODE REVIEW

**Comment by Ofish-Ofish** [comment]
i decided to also vary the size of each pedal to try making to flower more realistic

**Comment by leomcelroy** [comment]
I like how this has seeds but the drawing doesn't seem to be parametric. There should be some parameters to adjust or the ability to run it multiple times and get new flowers.

**Comment by Ofish-Ofish** [comment]
Hey thanks for you comment, I added 2 new variable that let you adjust the flower size and flower location to help bring more variation.
I hope this addressed your comment

**Comment by Ofish-Ofish** [comment]
Hey, I made some new changes,
there are now 7 different parameters you can change in order to generate different flowers.
the stem can curve now and you can change the amount/direction/ and thickness using parameters .
the petals and stems are colored and you can control their size/ and the amount they vary with parameters.

**Comment by Ofish-Ofish** [comment]
sunflower1

**Comment by leomcelroy** [comment]
This is looking really close. Can you clip the stem so we can't see it in the center?

**Comment by Ofish-Ofish** [comment]
Fixed the stem in the middle issue.
added new variables that let you control the amount of variation of space between each petal, and arc thickness.
I also added a variable that lets you choose if you want to center colored to make sure it can be turned off if the blot can't draw it.
sunflower4
sunflower2

**Comment by leomcelroy** [comment]
Nice congrats you've earned your Blot. You can order it [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw).

**Pull request merged**
