### PR TITLE
flower-michaelcoluccio

### PR DESCRIPTION
**Pull request by blueboy8137**

### CODE REVIEW

**Comment by blueboy8137** [comment]
image
It was a fun experience trying to make something that looks good but can also be randimized. I drew a flower with different leave and flower heights with different colors.

**Comment by leomcelroy** [comment]
Thanks for the submission. Can you please remove the spaces from the snapshot names and make sure the metadata references one of them in this line:

```
//@snapshot: blooming flower
```

It should be the name of one of the files with `.png` extension.

**Comment by blueboy8137** [comment]
> Thanks for the submission. Can you please remove the spaces from the snapshot names and make sure the metadata references one of them in this line:
> 
> ```
> //@snapshot: blooming flower
> ```
> 
> It should be the name of one of the files with `.png` extension.

How do i edit the already submitted file name’s

**Comment by blueboy8137** [comment]
Hi I changed the code to. Does it fit the criteria now?

**Review by maxwofford — CHANGES_REQUESTED** [review]
Nice improvement, but I think you can go even further. Check out these [cool](https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/BeautifulSaturn-AlexB/index.js) [examples](https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/ArtisticUniqueTrees-Hayden/index.js) from the gallery that just got approved recently! Just some thoughts:

- different numbers of leafs
- different shapes of petals
- multiple flowers!

**Comment by blueboy8137** [comment]
Hi Thank you I will try to work on it, but I wanted to get the blot machine to show at a summer STEM camp for kids in 2 Mondays from now. Is there any way I can get it before then?Thank you,Michael ColuccioOn Jul 15, 2024, at 5:32 PM, Max Wofford ***@***.***> wrote:﻿
@maxwofford requested changes on this pull request.

Nice improvement, but I think you can go even further. Check out these cool examples from the gallery that just got approved recently! Just some thoughts:

different numbers of leafs
different shapes of petals
multiple flowers!

**Comment by maxwofford** [comment]
@blueboy8137 we're backordered on blots right now and it wouldn't reach you in time even if the PR were approved! Right now just focus on improving that example and I'll see what I can do to get it ordered faster.

**Comment by blueboy8137** [comment]
I already updated the code can you see it?

**Comment by maxwofford** [comment]
Just checking in @blueboy8137, if you updated your code in the blot editor you'll also need to add your new code to the PR.

If you need help you can do that in the slack in the #blot channel!

**Comment by blueboy8137** [comment]
I did update the code did it not work?

**Pull request closed without merging**
