### PR TITLE
Dark Mode

### LINKED ISSUE #174: color contrast
Maybe it's just my perception but the contrast of blue and white can be uncomfortable in the long term

### LINKED ISSUE #194: Dark mode or customizable pallette
Know this seems extravagant, but I find I'm most creative at night and really want to use blot on a dark screen.

I'm 100% ok with not having official support for dark mode; but currently the way the turtle is rendered, extensions like "dark reader" will black out the canvas entirely:

Screenshot 2023-12-01 at 12 59 39

Short of a full dark-mode, I'd like the ability just to change the color of the pen in the renderer to work with the extension.

### PR DESCRIPTION
**Pull request by BrightTheBackpack**
the error module dark mode is a little meh, lmk what you think
closes #174 
closes #194

### CODE REVIEW

**Comment by leomcelroy** [comment]
Really nice to see this come in. I see a few things aren't covered with the PR. Dropdown menus are one, and the code blocks in the help window seem off too. I attached some screenshots below.


Screenshot 2024-06-04 at 11 15 59 AM

Screenshot 2024-06-04 at 11 16 06 AM

**Comment by BrightTheBackpack** [comment]
Fixed those! Also changed the help tabs a little bit. Let me know if there's anything else you want changed!

**Comment by leomcelroy** [comment]
Good progress. How about the modals?

There are modals for the file/log-in menus.

Screenshot 2024-06-27 at 10 58 24 PM

**Comment by BrightTheBackpack** [comment]
oof i forgot those existed. I'll try and to do asap

**Comment by BrightTheBackpack** [comment]
i'm at the powerpoint party at uvm rn, i'll get started right after that

**Comment by BrightTheBackpack** [comment]
done! i also moved all the colors to variables to make it easier to make changes in the furture, and changed up the help/toolbox menu a little bit.

**Comment by leomcelroy** [comment]
This is very close!

The text contrast is messed up on every other item in the modal.

Screenshot 2024-07-12 at 3 13 08 PM

**Comment by leomcelroy** [comment]
I think it would be good to make the color more blue too. With that being Blot's brand. Perhaps something like #1c2e73

**Comment by BrightTheBackpack** [comment]
good catch! i darkened the other itmes so the contrast is better, and i also made it more bluer

**Comment by maxwofford** [comment]
This looks awesome! I'm going to merge this & get community feedback!

**Comment by matytyma** [comment]
links have same color as regular text in the toolkit window

**Comment by BrightTheBackpack** [comment]
1. for the links, do we want:
Red for light mode
x(suggestions open) for dark mode
or
Blue for light mode
Dark blue for light mode.
The first one reflects whats on the home page, but i think i might like the second one a little more.
2. Any color suggestions for spoilers and error popups?
3. fixed

**Pull request merged**
