### PR TITLE
MiniCat-Armaanpreet

### PR DESCRIPTION
**Pull request by 4n0nym0u5-3y3**
My artwork is a digital representation of a Mini Cat created through coding. Using JavaScript and simple geometric shapes defined by mathematical formulas, I've constructed a charming depiction of Mini Cat with distinct features such as its round head, ears, eyes, nose, mouth, and paws. Each element, from the smooth curves of its head to the circular shapes representing its eyes and paws, is meticulously drawn using basic drawing primitives and mathematical calculations.

Coding this artwork was an engaging experience that combined creativity with technical skill. It involved planning out the composition using coordinates and dimensions, implementing algorithms to draw circles and lines, and iterating to refine details like shading and proportion. Each part of the Mini Cat, from its ears to its hands, required careful consideration of positioning and size to ensure the overall balance and appeal of the artwork.

I enjoyed the challenge of translating artistic vision into code. It allowed me to explore the intersection of art and programming, leveraging logic and creativity simultaneously. Adjusting parameters such as segment counts for smoother curves or adding subtle shading for depth provided opportunities to refine and enhance the visual impact of the Mini Cat illustration.

Overall, coding this artwork was not only about creating a visual representation but also about the journey of problem-solving and iterative improvement. It underscored the versatility of coding as a medium for artistic expression, where precise calculations and algorithms converge to produce visually compelling results.

### CODE REVIEW

**Comment by leomcelroy** [comment]
Thanks for the submission. Could you merge some of the circles together?

**Comment by 4n0nym0u5-3y3** [comment]
yes

**Comment by 4n0nym0u5-3y3** [comment]
yes

**Comment by 4n0nym0u5-3y3** [comment]
Hi, how long it takes to approve my drawing

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @4n0nym0u5-3y3– this is a good start but I don't think it meets the requirement for [being generative](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#1-make-a-unique-piece-of-generative-art)! Could you play with this a bit more and make it generate a new cat every time so I can merge your PR?

**Comment by 4n0nym0u5-3y3** [comment]
Ok

**Comment by 4n0nym0u5-3y3** [comment]
i changed the script

**Comment by 4n0nym0u5-3y3** [comment]
Hi, i updated my file from index,js.js -> index.js

**Comment by maxwofford** [comment]
Nice work @4n0nym0u5-3y3, now update the screenshots so i can see your new generative code!

**Comment by 4n0nym0u5-3y3** [comment]
i created a new pull request because i had problems to update my snapshots

Screenshot (71)

**Comment by 4n0nym0u5-3y3** [comment]
I'm having problems to update snapshots what can i do?

**Comment by maxwofford** [comment]
Post in the slack if you need help getting the PR updated! Maybe someone there can help.

**Comment by 4n0nym0u5-3y3** [comment]
snapshots updated

**Comment by 4n0nym0u5-3y3** [comment]
> Post in the slack if you need help getting the PR updated! Maybe someone there can help.

Hi, updated snapshots and  my file from index,js.js -> index.js

**Comment by BrightTheBackpack** [comment]
Could you rename the snapshots so theres no spaces, and change the metadata of your index.js(this part:/*
@title: MiniCat
@author: Armaanpreet Singh
@snapshot: snapshot.png
*/)
to have a snapshot thats in the folder?

**Comment by 4n0nym0u5-3y3** [comment]
> Could you rename the snapshots so theres no spaces, and change the metadata of your index.js(this part:/* @title: MiniCat @author: Armaanpreet Singh @snapshot: snapshot.png */) to have a snapshot thats in the folder?

done i  renamed the snapshots and metadata

**Comment by BrightTheBackpack** [comment]
oh and can you make the snapshots only of the art? the snapshot is what its going to show in the gallery: https://blot.hackclub.com/gallery

**Comment by 4n0nym0u5-3y3** [comment]
> oh and can you make the snapshots only of the art? the snapshot is what its going to show in the gallery: https://blot.hackclub.com/gallery

uploded new  snapshots

**Comment by BrightTheBackpack** [comment]
Also just an FYI, using math.random() instead of bt.randInRange(min: number, max: number) may make it so what is on the preview and whats drawn by the blot different

**Comment by 4n0nym0u5-3y3** [comment]
> Also just an FYI, using math.random() instead of bt.randInRange(min: number, max: number) may make it so what is on the preview and whats drawn by the blot different

So the code is fine as it is

**Comment by 4n0nym0u5-3y3** [comment]
> Also just an FYI, using math.random() instead of bt.randInRange(min: number, max: number) may make it so what is on the preview and whats drawn by the blot different

So the code is fine as it is

**Comment by BrightTheBackpack** [comment]
It would be better to change it to use the toolkit function(I think it might even be a requirement now)

**Comment by 4n0nym0u5-3y3** [comment]
> It would be better to change it to use the toolkit function(I think it might even be a requirement now)

i updated my code

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
i really like the googly eyes effect! Could you make it so the body does intrude too much onto the eyes? 
image

**Comment by 4n0nym0u5-3y3** [comment]
> i really like the googly eyes effect! Could you make it so the body does intrude too much onto the eyes? image

that's not good!

**Comment by 4n0nym0u5-3y3** [comment]
So it's approved my project

**Comment by 4n0nym0u5-3y3** [comment]
??

**Comment by 4n0nym0u5-3y3** [comment]
i have to update something

**Review by qcoral — CHANGES_REQUESTED** [review]
Hey, I like the idea and aesthetic of the design, but I feel as though you can polish this even more - could you keep working on this?

**Comment by 4n0nym0u5-3y3** [comment]
i updated my code

**Comment by 4n0nym0u5-3y3** [comment]
i added somethigs  to make it cute

**Comment by 4n0nym0u5-3y3** [comment]
like bell

**Comment by 4n0nym0u5-3y3** [comment]
> i updated my code

.

**Review by qcoral — CHANGES_REQUESTED** [review]
I like the improvements! I think you could still polish this piece more though. Is there a way you can remove all the overlapping lines?

**Comment by 4n0nym0u5-3y3** [comment]
> I like the improvements! I think you could still polish this piece more though. Is there a way you can remove all the overlapping lines?

i will try

**Comment by 4n0nym0u5-3y3** [comment]
i tried but nothing

**Comment by M0HID** [comment]
Hi there! I’m closing this PR for now to clear up the repo. Once you’ve made your edits/improvements, please make a new PR and we can review it there!!

**Pull request closed without merging**
