### PR TITLE
GSLV.Mk.III-Samrat

### PR DESCRIPTION
**Pull request by samratbose10**
My artwork features the GSLV Mk.III, a rocket developed by ISRO. The illustration captures the transition of the rocket launching into space, depicting the liftoff, the ascent through the atmosphere, and the final journey into the vast expanse of space. The artwork aims to convey the excitement and wonder of space exploration.

It's my 3rd PR and I'm nervous this time, but the experience was really great and I have really learned about Blot. Before this project, I had created a code which would draw your picture, but due to some issues, that didn't make it. This time, after a month, I'm submitting this PR and the journey was really great.

Here's the snapshot of one of the phase
snapshot2

### CODE REVIEW

**Comment by leomcelroy** [comment]
Thanks for the submission. I would accept this but you need some minor corrections.

The javascript file should be called `index.js` and the images folder should be called `snapshots` not snapshot.

**Comment by samratbose10** [comment]
I've made the changes: the JavaScript file is now index.js and the images folder is snapshots.

**Comment by leomcelroy** [comment]
Okay the name of the snapshot was still wrong but I fixed it for you.

You can order your Blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw), congrats.

**Comment by samratbose10** [comment]
Wooooo Hooooooo yayyyyyy it got accepted! I'm so thrilled and can't stop smiling. It's such a fantastic feeling! Thank you so much..... Yayyyyyyyyyyyy

**Pull request merged**
