### PR TITLE
CustomFlower-Narasimha

### PR DESCRIPTION
**Pull request by narasimha-1511**
I have made a pice of custom flower in the reverse direction 

image

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @narasimha-1511, this is an awesome start but you can do better! Really mix it up... what if you...

- made it different sizes with random leaf placement
- created a field of flowers
- made it more realistic looking!

Check out https://turtletoy.net/ for more inspiration!

**Comment by narasimha-1511** [comment]
Screenshot 2024-07-16 141702
Hey @maxwofford Check this out!!

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is looking really good! I think it's almost ready, but you should modify your safe area stuff to make sure you aren't drawing too many lines over eachother. I think the overlaping flowers will cause the pen to tear the paper

**Comment by maxwofford** [comment]
I haven't heard anything so I'm going to go ahead and close this for now so it's not in my re-review list. If you want to keep working on it just let me know and we can re-open this PR for now!

**Pull request closed without merging**
