### PR TITLE
SnowflakeBanquet-Ankita

### PR DESCRIPTION
**Pull request by eyestare**
This is my art piece, which I call a "Flower Banquet." You can add as many flowers as you like, change the line color, and play around with the colors to fill them as well. You can also adjust the size and the number of petals. I put instructions on how to change these all in the comments of my code! They also look like snowflakes, so that's what I really like about them. 

I've never made a program like this before, so I had to look through a lot of the guides to learn how to do this kind of thing. I struggled a lot, and redid it a bunch of times, but it ended up looking really smooth in the end!

snapshot1

### CODE REVIEW

**Comment by BrightTheBackpack** [comment]
(DW about the failed check, i'll review this soon)

**Comment by eyestare** [comment]
Hey Max, I made a few edits to match the code with the generated image. 

I'm a little confused by what you mean by generative. Please let me know what additional changes are needed to be made! :)

Thanks so much for the review!

**Review by maxwofford — CHANGES_REQUESTED** [review]
The code should generate a new piece of artwork that looks nice each time it's run! Check this out for details https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md#1-make-a-unique-piece-of-generative-art

**Comment by eyestare** [comment]
Hey Max, I made a few changes. Please let me know if it's okay! :)

**Pull request closed without merging**
