### PR TITLE
spiro_grad-subarctic

### PR DESCRIPTION
**Pull request by sub-arctic**
snapshot_3
*Note: the exported and attached images seem to have a thicker line width than what is visible in the editor, however this isn't a terrible thing*
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
I think this is really pretty, but it's very reliant on color to look good. On an actual Blot, it'd look more like this: 
image

Could you try and make it work without color? I think the patterns could wind up being really cool

**Comment by sub-arctic** [comment]
@qcoral - I've just set the output to a solid color. Let me know if something more detailed or unique is required, and I will be happy to provide :)

**Comment by qcoral** [comment]
This art piece is currently generated in a really straightforward algorithmic manner. Can you change it so that it has more creative intent?

**Comment by sub-arctic** [comment]
I've created a new (better) Blot project, so I will close this one since the new project is a successor and significantly different from the current one.

**Pull request closed without merging**
