### PR TITLE
GenerativeClock-JackF

### PR DESCRIPTION
**Pull request by JacksonFlanders**
This art is literally just a randomly generating clock, simple but beautiful in it's own way. It's also technically correct twice a day (ish). My experience with coding is very minimal, but I understand well enough to get simple projects done and understand what i'm doing. This was my second project because my first one didn't meet the req. (forgot to read them) :/

clock1

### CODE REVIEW

**Comment by leomcelroy** [comment]
Could you make it so you can type in the time? Maybe also make one hand clip the other.

**Comment by JacksonFlanders** [comment]
Ok, I got the hands able to be set at a certain time AND the hour hand will
be in a slightly different angle depending on the minute, just like a real
clock, hr =(hour*30)+([minute*6]/12) is the formula. I also figured out how
to make a circle. With all these giant changes, I would like to basically
submit a whole new PR, with different code and screenshots. How would I do
that? Would I just delete my old PR and submit a new one?

**Comment by leomcelroy** [comment]
Yes you can just make a new PR. You can make a new branch and make a PR from that.

**Comment by JacksonFlanders** [comment]
Ok, thanks

**Comment by JacksonFlanders** [comment]
I got the new one on the github, it's called GenerativeClockV2. I deleted
the old directory

**Comment by JacksonFlanders** [comment]
im pretty sure it's still in the same PR, that's what github thinks

**Comment by leomcelroy** [comment]
Congrats, you can order your Blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw).

**Pull request merged**
