### PR TITLE
BlottleShip-LinusC

### PR DESCRIPTION
**Pull request by LinuxDinoGitHub**
My artwork is a battleship board that can be playable and scalable (also responsive) when drawn. I intended this artwork to be interactive and admirable simultaneously, with the mesmerising grid pattern and captivating ship details. I am 13 y/o and have been learning programming for around 1 year, with beginner to intermediate experience in Javascript, React (& Native), C, C++, C#, Kotlin, HTML & CSS (Since 2021), and Python. My most proficient language should be Python since my school uses it to teach CS concepts. My first experience with JavaScript was an inter-school hackathon in November of 2023, which was my first time programming (By the way, I chose JavaScript due to my teammate's preference, and we got to the podium (3rd place) in that hackathon).
I think I worked 10+ hours on this project and I'm quite proud of the maths I learnt from it, especially trigonometry.
Blottleship

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [x] Optional, if you remixed this from something else, mention it here: **Scott C - wordsearch** - Obtained most text engine commands from here (only the commands, not the engine)

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
This is pretty cool! For some of the ships, its kind of hard to tell how many spaces it takes up
image
Also, can you make sure your metadata @snapshot feild includes .png at the end?

**Comment by LinuxDinoGitHub** [comment]
Changes requested complete, thanks for the feedback!

**Review by BrightTheBackpack — APPROVED** [review]
this looks pretty cool! Max will be back soon to do a final review

**Comment by BrightTheBackpack** [comment]
could you also make the sure the metadata has the same capitlization as the snapshot file name?

**Comment by LinuxDinoGitHub** [comment]
Yup, changed it to lowercase (lol I didn't see sry)

**Review by maxwofford — APPROVED** [review]
Nice work on this! I love how you changed it up a bunch with the ship parts. Go ahead and [order your kit](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
