### PR TITLE
cuteOneLineFlower-emma

### PR DESCRIPTION
**Pull request by emma-x1**
Generates a three-petal colored flower. Uses random seed value to move the position of the flower, stem, and leaves, as well as change the shape of the petals slightly. This is my first coding project and I'm a beginner coder :)
line_flower3

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)

- [ ] Optional, if you used a tutorial or based your art on something else, please include the link here:
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by BrightTheBackpack — CHANGES_REQUESTED** [review]
Wow this is a pretty flower!
It think it would be cool to see a flower field with multiple random flowers.
It would also be cool if some flowers had 1 leaf, and some had 2

**Review by BrightTheBackpack — APPROVED** [review]
nice! Max will be back soon to do a final review

**Review by maxwofford — CHANGES_REQUESTED** [review]
This looks great but I think you should step it up a little bit more! Make the petals change their size individually, give the leafs veins, that sort of thing!

**Comment by qcoral** [comment]
Seeing as this hasn't been updated in over a month, I'm going to close the PR for now. You're free to make a new one in the future with the same artwork if you'd like! Reach out to me @ alexren on the slack if you have any questions!

**Pull request closed without merging**
