### PR TITLE
Baseballfield-Ventengo

### PR DESCRIPTION
**Pull request by Ventengo1**
My art piece is of a baseball field. I included the infield with the four bases as well as the pitchers mound. I also included the  outfield fence and made sure to leave room past it just like in a real field. I have some experience coding in Java script but more in other languages. I learned a lot while coding this project. 

pic1

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here: https://blot.hackclub.com/editor?guide=start

### CODE REVIEW

**Comment by Ventengo1** [comment]
IMG_3017

**Review by maxwofford — CHANGES_REQUESTED** [review]
It doesn't look like this piece is generative!

**Comment by Ventengo1** [comment]
What do you mean by generative? I have lots of variables throughout the code which can be changed altering the image. For example the large curve on the left side of the image can be flipped or the amount of arc can be changed layering how it would look. Also the size of the squares can also be changed altering the look.

**Comment by Ventengo1** [comment]
There are more examples too with the positions of the squares, the size of the circle in the middle, and more

**Comment by qcoral** [comment]
Hey, I did a check and this is indeed generative, but 2 things:

1. Could you move the variables to the top so that they can easily be changed?
2. This drawing is a little simple, could you work on it more?

I'll swing back around later, thanks for the wait!

**Comment by Ventengo1** [comment]
Updated the PR with new code an image.
pic1

**Review by qcoral — CHANGES_REQUESTED** [review]
This is better, but still could use some more work. Also, can you move the variables at the top? Makes it much easier for someone to see the different generations of your artwork!

**Comment by Ventengo1** [comment]
Moved all variables to top and added more to code. 
pic1

**Comment by Ventengo1** [comment]
Just updated code and polished it up.
pic1

**Comment by Ventengo1** [comment]
Just updated code: 
pic1

**Comment by Ventengo1** [comment]
pic2

**Comment by Ventengo1** [comment]
pic3

**Comment by Ventengo1** [comment]
Just updated with more
pic2
pic1
pic3
 random variables

**Comment by Ventengo1** [comment]
P
pic1
pic2
pic3
olished up code and now I feel it looks good.

**Comment by Ventengo1** [comment]
Just updated code by adding word 'Rockies' to it. 
image

**Comment by Ventengo1** [comment]
image (1)

**Review by qcoral — CHANGES_REQUESTED** [review]
This is getting there!! But there's still a ton of overlapping & generally unpolished parts. Can you try and clean things up? I'm specifically looking at the players, as I'm pretty sure they aren't so uncoordinated in real baseball :)

**Comment by Ventengo1** [comment]
Just updated code and made it look a lot cleaner. 
image (2)

**Comment by Ventengo1** [comment]
Made it look a lot more realistic by adding people at the bases and on the field

**Comment by EmperorNumerius** [comment]
Hi there,
This is a cool piece of artwork but it needs to have less overlapping
You are well on your way to having a blot. howvever its a bit simple and overlaps quite a lot

**Comment by Dongathan-Jong** [comment]
Keep working on your PR! Just an update, I am going to close this PR. Please create a new PR once you have updated your art. I am doing this due to a new management system for the PRs.

**Pull request closed without merging**
