### PR TITLE
LineyPeaks-Jannik

### PR DESCRIPTION
**Pull request by playlogo**
## Check list
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] **Could overlap lines more than 5 times** But only for short distances and it would contribute to the wanted look
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:
None

## A short description
This artwork is my first (and completely self-made, thus very inefficient) implementation of a Gas Simulation, made to look nice.

How it works:
- I generate 1-3 randomly rotated two-dimensional functions to serve as the initial pressure values for my gas particles. (This step is only necessary to create art, not simulate a gas :) )
- I then interpolate the pressure between the points to create a continuous map of pressure. (This step can be used to render the simulation.)
- Finally, I use the map created in the previous step to determine where the gas particles "would like to go". These are displayed by the lines.
- [In a real gas simulation, I would now move the gas particles and repeat!]

Although the code isn't extremely long, I've done a lot of research into fluid (and gas) simulations and the (for me still somewhat magical) math behind it.

Even if this art might not be good enough for a machine, I still want to say thank you for giving me the motivation to finally approach this new topic and start learning about it!

A Image:

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Super awesome backstory into how you created this! This is pretty close to being merged, but falls just a tad bit below the bar! Do you think you could add something that would really give it a wow factor? Once completed I can forward this to Alex for approval :)

**Comment by playlogo** [comment]
Hey, I think I found the missing wow factor! :)
It's now much cleaner and more organized, but it still contains all the scientific background it had before. 
In fact, it now displays the movement of the gas particles and, when looking at it from farther away, also the pressure of the whole gas! The darker it is, the higher the pressure!

Here's my favorite result:


I've also cleaned up the code and improved the documentation!

**Comment by Dongathan-Jong** [comment]
Great! I will forward this to Alex for approval, and it may take anywhere from a couple days to a couple weeks to receive a response. Please be patient!

**Comment by qcoral** [comment]
This is a really cool demo! I think it would be a lot greater if you gave people options to mess with the initial 2D functions more, but it's still really cool regardless. Congrats! You can get a blot [here](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
