### PR TITLE
lorenz-omay

### PR DESCRIPTION
**Pull request by Omay238**
this is a remake of the lorenz attractor I made for the blot a year ago. lost the code for it. misunderstood the requirements for submission at one point and didn't make anything new for a year. well now I'm gonna make more stuff for the blot.

here's the image I am required to put in. just the basic lorenz attractor image
lorenz1

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [x] Optional, if you used a tutorial or based your art on something else, please include the link here:
https://en.wikipedia.org/wiki/Lorenz_system
- [ ] Optional, if you remixed this from something else, mention it here:

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
This is cool! Can you change the variables to be random so that each time the program runs the image is different?

**Comment by Omay238** [comment]
It is done.

**Comment by qcoral** [comment]
Nice work! This is pretty cool to play around with. One thing i'd love to see would be some sort of comment explaining what a lorenz attractor is!

**Comment by Omay238** [comment]
Ok, done. I also put in a Wikipedia link for much more detailed information

**Comment by Omay238** [comment]
@qcoral

**Comment by Omay238** [comment]
@qcoral i am once again requesting a review

**Comment by Omay238** [comment]
I'm gonna close this so I can reorganize my fork.

**Pull request closed without merging**
