### PR TITLE
snowyhouse_dexter

### PR DESCRIPTION
**Pull request by Speedlet2**
Hi! My name's Dexter! I'm 16, and live in the UK. I currently go to Sixth Form (similar to the higher grades in american high school), and do computer science! I've mostly ever done python and C# programming, but I've been experimenting with JS with blot and sprig! This is my second attempt at a PR, and hopefully you like it! As it's nearly christmas, I thought I'd make a classic christmas scene with the twist of being dependent on the ratio so it can be stretched in the X and Y direction! Hope you enjoy :0

### CODE REVIEW

**Comment by Speedlet2** [comment]
image (2)
image (1)
image

Here's some example images of the stretching functions!

**Comment by Speedlet2** [comment]
To explain my artwork, I use a function to draw all of the larger sqares shown in the artwork, and use another function to  draw all of the lines (including the roof and window frames. I then use the integer random function built into the langauge to generate positions for all of the "snowflakes" so that they don't go below the house, outside of the drawable area or below the base of the house. All of the "snowflakes" are drawn using the arc command set at 360 degrees.

**Comment by leomcelroy** [comment]
Nice happy to see a second commit. I think you're on the right track. Could you make sure the windows scale properly when the house is adjusted? When that is done I think we're ready to merge.

**Comment by leomcelroy** [comment]
An elevated version of this could be something like below:

Screenshot 2023-12-19 at 10 50 49 AM

**Comment by Speedlet2** [comment]
Sounds great! I'll give that a go and send you a ping on slack when it's done!

**Comment by leomcelroy** [comment]
Going to close for now but please reopen with updates. Looking forward to it!

**Pull request closed without merging**
