### PR TITLE
Desert-minimal-Nikhil

### PR DESCRIPTION
**Pull request by NIKHIL2XD**
- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I am submitting art that...
  - [x] is algorithmically generated (will change each time the program is run)
  - [x] is drawable on a blot (fits in the work area & doesn't overlap too much)
  - [x] is original (not copied from somewhere else)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))

- [x] Optional, if you used a tutorial or based your art on something else, please include the link here: I used mixture of these tutorials to build this design - https://blot.hackclub.com/editor?guide=start https://blot.hackclub.com/editor?guide=square-disarray
- [x] Optional, if you remixed this from something else, mention it here: I took inspiration from DesertSunset-Augustin and tried to make it my own way - https://github.com/hackclub/blot/tree/main/art/DesertSunset-Augustin

### CODE REVIEW

**Comment by NIKHIL2XD** [comment]
This is for the first time i have learned javascript for blot and thanks Bright Li to helping me out to learn this ❤️

**Review by maxwofford — CHANGES_REQUESTED** [review]
This looks awesome & is a great start! A couple things to change though:

- mention the tutorial & piece you remixed
- the art sometimes makes it out of the bounding box (specifically around the sun), maybe you can add some code to prevent that
- each generation looks a little bit the same due to the position & number of cacti & mountains, maybe you can make that change with each generation

**Comment by NIKHIL2XD** [comment]
Ohh sorry, just a second

**Comment by NIKHIL2XD** [comment]
Done !

**Comment by NIKHIL2XD** [comment]
Fixed the issue of art going out of the bounding box

**Comment by NIKHIL2XD** [comment]
Tried to change few values so cactus and mountain will not look same on each generation
I tried my best to find the best possible solution to resolve these issues, if still there is anything left please let me know i'll try to fix that too.

**Review by maxwofford — APPROVED** [review]
Nice work on this, I'm merging it! You can go ahead and order [your blot kit](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)

**Pull request merged**
