### PR TITLE
Skyscrappers_in_the_starry_sky-Creeperlulu

### PR DESCRIPTION
**Pull request by creeperlulu**
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

My artwork represents skyscrapers in the starry night, with a big moon in the background. I really enjoyed working on this! I never used Javascript this much, this was a good practice for me. I only had issues with the starry sky, it was pain to code and I nearly gave up but I managed to finish it (kinda proud of me lol)

- [✓] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [✓] I am submitting art that...
  - [✓] is algorithmically generated (will meaningfully change each time the program is run)
  - [✓] is your own work that is not copied from somewhere else
  - [✓] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [✓] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [✓] Doesn't overlap lines more than 5 times
    - [✓] Fits in the working area of 125x125mm
    - [✓] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here: Nope, all my work :D

Lastly, link a picture of your art piece here: 
image

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
This is fantastic! I love the night sky, especially here in Vermont where the air is so clear. I think you're pretty close, but I'd love to see some more detail in your art piece.

**Comment by creeperlulu** [comment]
@qcoral Added some water and craters to the moon! Do I have to do anything else (like create another pull request) ?
Thanks a lot :)

**Comment by qcoral** [comment]
It's alot nicer! I couldn't help but notice that the artwork seems to clip out of the bottom - could you fix that?

**Comment by creeperlulu** [comment]
Clip out?? Where does it clip out? I don't see anything... :/
image

**Review by qcoral — CHANGES_REQUESTED** [review]
My apologies! Was an oversight with the water waves. I think this piece is really close, but if you could make the craters avoid overlapping with each other and look a little more detailed I think that would make it! Also, if the buildings could show up behind the shoreline, that'd be great.

**Comment by M0HID** [comment]
Hi there! Just an update - I'm closing this PR for now to clear up the repo. Once you're done with your edits/changes, please make a new PR and we can review it there!

**Pull request closed without merging**
